### ISSUE TITLE
[Bug] 关于页面邮箱地址链接故障

### ISSUE THREAD

**Issue by Clansty** [mtf-wiki/MtF-Wiki#127]
Hugo 自动将关于页面内 SVG 中的邮箱地址转换成了 `/mailto:...` 的链接，导致出现了一些问题。而我下载仓库自行编译测试时发现 Hugo 并没有在 `mailto` 前加 `/`。我觉得应该是我本地使用的 Hugo 版本较新（`v0.82.1+extended`），已经修复了这个问题

解决办法可能是更新 Github Action 使用的 Hugo 版本

![错误的链接效果](https://user-images.githubusercontent.com/18461360/131627546-81aafbe0-4ac6-42ed-a688-ac8ae1ff7c0a.png)  
错误的链接效果

![导致错误的代码](https://user-images.githubusercontent.com/18461360/131628197-a8c4d4ee-5182-4f46-8da6-63d730dba5ec.png)  
导致错误的代码

![本地编译是无此错误](https://user-images.githubusercontent.com/18461360/131628069-f271573b-3e7d-47c3-b46e-c7d16eb232e5.png)  
本地编译是无此错误

**Comment by septs** [comment]
这个问题的 root cause 是我们所使用的 zdoc 主题

https://github.com/mtf-wiki/hugo-theme-zdoc/blob/784a1ecaf9e612948af613ee7142956a96b46d06/layouts/_default/_markup/render-link.html

自动为 destination 使用了 `relURL` 以至于最终结果变成这样，目前已修复
