### ISSUE TITLE
关于心理量表的一些建议

### ISSUE THREAD

**Issue by wychlw** [mtf-wiki/MtF-Wiki#133]
鉴于大部分 MtF 都有着或多或少的心理问题，可否考虑在 wiki 上设立一个在线心理量表，以便于大家了解自己的的心理状态？

**Comment by septs** [comment]
目前只是初步整理，后续计划尚未考虑。

**Comment by llh721113** [comment]
我觉得应该有一个提示“量表仅供参考，请以实际情况为准”

**Comment by septs** [comment]
另外我们缺乏大部分量表程序的逻辑细节，因此无法制作开源的量表实现。

**Comment by septs** [comment]
> 我觉得应该有一个提示“量表仅供参考，请以实际情况为准”

考虑到刷分的客观事实存在，提供便捷的在线量表支持

在结果上会导致量表的客观性失去（虽然有些量表在客观上已经 outdated 了）

**Comment by sceext2** [comment]
有一些现成的免费在线心理测试, 可以考虑加链接推荐  

收费的如果不是很贵, 也可以考虑  

如果情况严重还是建议去医院精神科

**Comment by wychlw** [comment]
关于实现细节可以先从简单一些的SAS，SDS先做起来？
然后关于刷分的问题...对于要使用的量表，网路上基本都可以通过搜索/查资料来刷，而这样一个类似汇总或者其它的个人感觉反而可以让她们由于没有其它顾及了解的更现实一点？
（个人片面的观点吧...就...有什么问题喷就行喵）

**Comment by septs** [comment]
主要是还是担心主观刷分带来的影响
不然我自己写一套更好用的全开源实现并不难

**Comment by wychlw** [comment]
刷分确实在我提出建议之前仔细考虑过...自己根据网上所有的东西也试过一下...确实有了量表之后做几遍基本就能猜出来了
但同时...我也亲手试过，带着某个妹妹去三甲精神科，她以前从来没碰过那些量表却仍然能通过自己的猜想做到从没事到重抑基本随便出，而且医生没有看出来问题
所以...这件事让我很怀疑，刷不刷分用处到底有多大

**Comment by wychlw** [comment]
主要...权衡这些确实太难了...
以后再说吧喵...？
