### ISSUE TITLE
建议开启discussions功能

### ISSUE THREAD

**Issue by Dringsim** [mtf-wiki/MtF-Wiki#164]
像 https://github.com/mtf-wiki/MtF-Wiki/issues/3 这样的内容就明显不适合放在issues里（

**Comment by Rinfair-CSP-A016** [comment]
你好！首先感谢你的建议！
discussions主要功能是给没有其它讨论方法的仓库/项目提供一个讨论平台。
目前MtF-Wiki已经有Telegram，Discord，QQ群等讨论平台，如果有类似上述issue的问题，完全可以通过以上平台/途径讨论，无需在本仓库开放discussion功能。
同时，开放discussion功能将会增加工作组的维护成本。
因此，我认为此建议不具有实施的必要性。
以上。

顺颂商祺
