### ISSUE TITLE
一些有用的资料链接

### ISSUE THREAD

**Issue by BikerDuality** [mtf-wiki/MtF-Wiki#165]
# 综述
- 等待WPATH护理标准v8(目前v7)  
预计2021年12月出版 
[WPATH护理标准](https://www.wpath.org/publications/soc)
# 工具
- [TransBox - HRT相关的小工具们](https://github.com/Pix-00/TransBox)
- ~~[transHelper跨儿助手](https://github.com/MsZhu-trans/transHelper-release)~~
# 文档库
- [Transgender-lost-years](https://github.com/KristallWang/Transgender-lost-years)
- [MtF Wiki](https://mtf.wiki/)
- [跨性别在线·文档库](https://docs.transonline.org.cn/)
# 指南
## 中文
- UpToDate  
[跨性别女性的评估和管理](https://www.uptodate.com/contents/zh-Hans/transgender-women-evaluation-and-management)  
[跨性别男性的评估与管理](https://www.uptodate.com/contents/zh-Hans/transgender-men-evaluation-and-management)
- [跨性别在线·文档库](https://docs.transonline.org.cn/)  
WPATH SOC V7，UCSF指南，内分泌协会指南(2017)，[UNDP]亚太跨性别健康蓝图
## 英文
-[wiki Portal:Transgender](https://en.wikipedia.org/wiki/Portal:Transgender)
英文维基百科信息非常齐全
- [Clinical Guidelines with Information on Transfeminine Hormone Therapy](https://transfemscience.org/articles/transfem-hormone-guidelines/)
transfemscience 专业程度非常高的站点
## ~~个人综述文章~~
~~可信度未知~~
- ~~[JANUARY 4, 2021 BY 神楽坂梓月(twitter @ziyue_shizuki)  
跨性别激素治疗（THT）指南 – 女性型](http://opengl106.oikawa.moe/2021/01/04/transgender-hormone-therapy-mtf-instructions/)~~
- ~~[MtF HRT 资料 (v1.05) by shizu twitter @shizunyan_](https://docs.google.com/presentation/d/1PzE-rmtwBMOrgXcsI_RIDAKTUIe3fx5h-PmEbzRgBBA/edit#slide=id.gd20f122bcb_13_0)~~

**Comment by BikerDuality** [comment]
我还有dunp成docx的uptodate文章不知道存哪里

**Comment by soragotosann** [comment]
模拟顺女生理期这个是没必要的…似乎已经是共识了吧…梓月那个用药方法不太靠谱的样子

**Comment by BikerDuality** [comment]
> 
> 
> 模拟顺女生理期这个是没必要的…似乎已经是共识了吧…梓月那个用药方法不太靠谱的样子

所以标记为可信度未知

**Comment by llh721113** [comment]
我大体看了一下季子越的文章，可以扔垃圾桶了

**Comment by BikerDuality** [comment]
希望各位大佬能麻烦一下把有用的链接并入wiki

**Comment by Rinfair-CSP-A016** [comment]
除以下部分问题所涉及到的内容以外，其它的都将在之后陆续引入Wiki：
1. TransHelper自6月起开发者已弃坑不再维护，软件核心bug很多，暂不引入。
2. WPATH护理标准版本较旧，将在新版发布后补入。
3. shizu的文档在部分关键信息上对学术论文的理解有误，暂时不会引入。
4. 梓月的HRT方案在可信度上难以服众，也不符合目前常规HRT用药剂量，不考虑引入。

最后感谢你提供的资料以及对Wiki的发展作出的贡献！祝生活愉快！

**Comment by BikerDuality** [comment]
> 
> 
> 除以下部分问题所涉及到的内容以外，其它的都将在之后陆续引入Wiki：
> 
>     1. TransHelper自6月起开发者已弃坑不再维护，软件核心bug很多，暂不引入。
> 
>     2. WPATH护理标准版本较旧，将在新版发布后补入。
> 
>     3. shizu的文档在部分关键信息上对学术论文的理解有误，暂时不会引入。
> 
>     4. 梓月的HRT方案在可信度上难以服众，也不符合目前常规HRT用药剂量，不考虑引入。
> 
> 
> 最后感谢你提供的资料以及对Wiki的发展作出的贡献！祝生活愉快！

已根据建议进行修改,多谢指正

**Comment by septs** [comment]
我认为 MtF.wiki 应当以 [循证医学](https://zh.wikipedia.org/zh-cn/循证医学) 为根基为读者提供可信的资料
对于一些 [替代医学](https://zh.wikipedia.org/zh-cn/替代医学) 的内容本人持反对意见（e.g: 模拟女性经期）

HRT 用药指导包括众多生理指标的长期跟踪，原则我们需要秉承着“谨遵医嘱，合理用药”来以此降低副作用带来的长期影响
因此原则上对于有条件的患者应当前往 [上海九院](https://mtf.wiki/zh-cn/docs/hrt/sh9/) / [北医三院](https://mtf.wiki/zh-cn/docs/hrt/pku3/) 接受长期 HRT 跟踪治疗

**Comment by BikerDuality** [comment]
转载链接
https://github.com/KristallWang/Transgender-lost-years/issues/62

**Comment by Dringsim** [comment]
考虑到你圈的实际情况，建议把 https://qingshanasd.cn/Medical-Map/ 也贴上（

**Comment by Clansty** [comment]
> 考虑到你圈的实际情况，建议把 https://qingshanasd.cn/Medical-Map/ 也贴上（

草，你圈人均 ADHD 是吧

**Comment by Dringsim** [comment]
https://diyhrt.github.io/
这里面的内容咋样👀

**Comment by septs** [comment]
上述链接均被收录至 https://kuaer.club

https://github.com/mtf-wiki/kuaer.club
