### ISSUE TITLE
建议打开仓库的 Discussion 功能，目前的讨论大多数都不能被称之为 issue

### ISSUE THREAD

**Issue by Misaka-0x447f** [mtf-wiki/MtF-Wiki#183]

**Comment by Rinfair-CSP-A016** [comment]
#164 已对此问题进行回复
目前我们仍保留该意见并有以下修改：QQ群目前不再作为主要交流平台，有问题可到telegram或discord对应频道中进行讨论。
祝生活愉快！

**Comment by Misaka-0x447f** [comment]
> #164 已对此问题进行回复 目前我们仍保留该意见并有以下修改：QQ群目前不再作为主要交流平台，有问题可到telegram或discord对应频道中进行讨论。 祝生活愉快！

如何找到 telegram 群组呢，readme 里没有

**Comment by Rinfair-CSP-A016** [comment]
> > #164 已对此问题进行回复 目前我们仍保留该意见并有以下修改：QQ群目前不再作为主要交流平台，有问题可到telegram或discord对应频道中进行讨论。 祝生活愉快！
> 
> 如何找到 telegram 群组呢，readme 里没有

目前telegram暂时不允许新成员加入，新成员请转至discord哦
