### ISSUE TITLE
建议添加Gitalk评论系统

### ISSUE THREAD

**Issue by SinKy-Yan** [mtf-wiki/MtF-Wiki#186]
有些页面可以加上评论吧，感觉可能会有点用？

**Comment by SinKy-Yan** [comment]
啊，还有那个医生的那些页面要不要放点医院的照片

**Comment by mis1042** [comment]
这个提议不错...?

**Comment by Rinfair-CSP-A016** [comment]
在wiki下增加评论区难以部署和管理，同时目前评论量与浏览量不成正比，在已有discord和telegram的情况下难以达到预期效果。综上，此建议将暂时搁置，待一定时机后重新讨论。
