### ISSUE TITLE
关于新条目...？

### ISSUE THREAD

**Issue by wychlw** [mtf-wiki/MtF-Wiki#23]
怎么说呢...
就是各地区的对trans友善/能进行帮助的组织，用不用开一个条目撰写一下
或者并不需要这部分内容咕噜...？

**Comment by saeziae** [comment]
赞成

**Comment by saeziae** [comment]
[公益组织 - MtF Wiki](https://mtf.wiki/zh-cn/docs/organizations/)

乁( ˙ ω˙乁)

欢迎帮助完善哦

**Comment by wychlw** [comment]
那...要不要最好按照地区什么的分一下类喵...？
