### ISSUE TITLE
补充 北京八大处医院 SRS 手术的技术细节

### ISSUE THREAD

**Issue by sceext2** [mtf-wiki/MtF-wiki#237]
对应 wiki 页面: <https://mtf.wiki/zh-cn/docs/srs/china/psh/>

资料来源: <https://card.weibo.com/article/m/show/id/2309404596235515330857>

关键词: `口腔粘膜微粒组合阴囊皮瓣阴道成形术`

重要部分引用:  

> 三、变性患者的阴道再造特点
> 
> 男-女变性患者会阴区域的治疗与46 XX DSD 的治疗有相似之处，也包含阴蒂成形、小阴唇成形、阴道成形和第二性征重塑等治疗步骤。但是也有其特点。
> 
> 1. 会阴体结构属于男性表现，局部致密而坚韧，一般建议造穴时应该锐性剥离结合钝性剥离，严防损伤直肠和尿道等结构。
> 
> 2. 变性患者阴囊组织特别丰富，单纯用来做大阴唇结构会有富余，因此进行阴道成形时可以部分采用阴囊结构，来形成阴道的下半和两侧，而阴道的上部则可以采用部分包皮结构，即形成小阴唇后剩余的部分，这样形成的阴道组织相对节省组织，但后期容易出现阴道内壁组织下滑现象，可以将下滑组织切除或者缝线固定。
> 
> 3. 有学者喜欢采用阴囊做大阴唇，阴茎包皮做小阴唇，采用结肠或回肠做阴道，外形可能更为逼真，但成形的阴道需要一定时间的扩张。
>
> 4. 我们采用部分阴囊皮瓣联合口腔黏膜微粒进行变性患者的阴道再造，取得一定的效果。优点是阴囊皮瓣下滑的比较轻，但是阴道口的外形略有不足。
> 

以上.

**Comment by sceext2** [comment]
又找到一篇更详细的论文, 链接: <https://d.wanfangdata.com.cn/conference/9075304>

标题: **阴囊皮瓣结合黏膜/皮肤微粒阴道再造在男变女变性手术中的应用**

摘要:

> 目的 介绍一种新的男变女变性手术的阴道再造方法. 
>
> 方法 采用男变女易性癖病人的阴囊皮瓣结合口腔黏膜、阴茎皮肤及尿道海绵体粘膜混合微粒再造阴道, 以带阴茎背血管神经蒂部分龟头组织再造阴蒂, 剩余阴囊皮瓣再造大阴唇, 阴茎皮瓣再造小阴唇及阴道前庭. 
>
> 结果 应用该新方法治疗 3 例男易性癖患者, 手术均在 289 分钟内 [分别为 278, 258, 289 分钟) 顺利完成. 术后随访 10-24 个月, 无严重并发症. 所有患者再造阴道均宽敞、湿润、光滑、对外阴形态满意, 生活状态良好. 2 例术后有性生活患者诉再造阴道有性快感, 性生活中无需润滑剂.

**Comment by Rinfair-CSP-A016** [comment]
请确认此技术是否被八大处医院列为 通用技术 而不是 实验性技术。
在确认后向我们反馈结果，以便能够及时更新此信息。

**Comment by septs** [comment]
由于长时间未跟进，请在重新确认后 reopen 本 issue

**Comment by sceext2** [comment]
医院医生: 中国医学科学院 整形外科医院 整形十科(妇科/体表肿瘤) 李强 (主任医师)  

确认时间: 2022-08-14  
确认方式: 面诊  

挂号方式 (之一): 微信公众号 中国医学科学院整形外科医院: 就诊服务 -> 预约挂号 -> 西院/东院 (两边都行) -> 整形美容外科 -> 整形十科 (妇科/体表肿瘤中心) -> 李强 (主任医师)  

出诊时间: 西院 周四上午, 周日上午.  东院 周二上午.  

----  

手术技术: 皮瓣  

口腔粘膜: 一般不使用, 但是材料不足时可以使用  

避免阴道内长毛的方法: 术前激光脱毛 (需要几个月时间), 脱毛不是必须的, 但是不脱毛就可能出现长毛问题  

手术费用: 约 5 ~ 6 万  

时间 (排队) 问题: 首先需要 伦理委员会审核, 但是伦理委员会召开时间不确定.  审核通过后很快就能手术 (几天至几周).  

----  

## 伦理委员会审核  

所需材料 (5 种):  

1. 易性症诊断证明  
2. 无精神疾病证明 (上海精神卫生中心 陆 的证明同时包含此项)  
3. 无犯罪记录证明  
4. 个人申请书 (公证)  
5. 父母知情同意声明 (公证)  

伦理委员会 开会 时, 本人必须到场, 父母建议到场 (非必须).  

医生不看材料, 让准备好之后, 直接打电话联系他的助手.  

----  

吐槽: 医生挺和蔼的, 并且看起来比照片上年轻 ;-)

**Comment by sceext2** [comment]
@septs  好像并不能 reopen, 没看到操作按钮, 可能是无权限操作

**Comment by Rinfair-CSP-A016** [comment]
请于术后提交照片材料便于我们进行评估，此内容将保留（

**Comment by sceext2** [comment]
目前窝已在上海手术, 因此关于此医院的情况不能继续更新.  

至今仍未等到此医院的伦理委员会通知.

**Comment by FangCunWuChang** [comment]
口腔黏膜和无疤痕技术已成为八大处的标准技术。

**Comment by FangCunWuChang** [comment]
八大处挂会阴整形与性别重塑科 李峰永。
术前需要材料为：
1. 精神科诊断证明书
2. 无犯罪记录证明
3. 个人申请书
4. 父母知情证明

材料均无需公证。

**Comment by FangCunWuChang** [comment]
手术费用大概10万左右，住院押金12万。
伦理会议大约每季度召开。
