### ISSUE TITLE
bug fix req

### ISSUE THREAD

**Issue by tuboshufps** [mtf-wiki/MtF-Wiki#257]
https://mtf.wiki/zh-cn/docs/medicine/hormone-check/
pre above
"促卵泡激素 和 [黄体化激素]({{ ref “#lh” }}) 在生殖相关的生理过程中协同发挥着至关重要的作用。"
“[黄体化激素]” are not hyperlinked to where it should be.
thx

**Comment by Rinfair-CSP-A016** [comment]
Bug has fixed due to commit 8517d94.
Thanks for your contribution to our project!
