### ISSUE TITLE
简体中文页面外链的本地优化

### ISSUE THREAD

**Issue by saeziae** [mtf-wiki/MtF-Wiki#289]
如在百度百科或其他科普内容准确的情况下，使用百度百科代替维基百科页面，找不到的也可用维基百科的镜像。
Android平台软件使用酷安等平台或镜像代替google play.

**Comment by septs** [comment]
考虑到国内受政策影响的风险
仍然需要保留 Wikipedia / Play Store 等原始发布源的链接作为备份

**Comment by Rinfair-CSP-A016** [comment]
建议同时添加维基百科、百度百科的链接

**Comment by saeziae** [comment]
搞定了。
