### ISSUE TITLE
报告新的SRS医生

### ISSUE THREAD

**Issue by Chiaki2333** [mtf-wiki/MtF-Wiki#310]

**Comment by Chiaki2333** [comment]
---
title: 暨南大学附属第一医院（广州华侨医院）｜刘宏伟
weight: 31
---

{{< doctor-image src="doctor.jpg" >}}

医生姓名：刘宏伟

所在医院：[暨南大学附属第一医院（广州华侨医院）](http://www.jd120.com/)(暨南大学附属第一医院（广州华侨医院）)

1989至1999年为解放军第四军医大学唐都医院整形外科硕士研究生、主治医师、讲师。 2000年至2004年为日本爱媛大学医学部第二外科客座研究员、博士研究生。 2003年9月获日本爱媛大学医学博士学位。 2004年至2006年为南方医科大学博士后流动站广州军区广州总医院博士后工作站整形外科博士后。 2007年至今任暨南大学附属第一医院整形外科主任、主任医师。 2009年起任再生医学教育部重点实验室学术带头人。 2010年7月获聘暨南大学整形外科学临床专业学位和科学学位博士研究生导师。 长期从事整形外科、美容外科、激光美容医学的临床和科研工作，在国内、外专业期刊发表论文150余篇，其中SCI收录期刊发表文章60余篇，是国家973计划（严重创伤救治与损伤组织修复的基础研究）03课题组重要成员，负责该课题子课题1项，国家自然科学基金面上项目5项，军队“十一五”规划医学科研基金1项。



## 前置条件

1. 未婚证明
2. 无犯罪记录证明（公安局出具）
3. 父母知情同意书（父母双方签字、按拇指手印，并需公证）
4. 本人知情同意书（本人签字、按拇指手印，并需公证）
5. 三甲医院精神心理科出具的“易性症”疾病诊断证明书
6. 近半年连续接受相关心理治疗病历记录
7. 多次前往医院咨询、要求性别重置手术

## 费用

**0深度**
0深度手术全部费用约为5万到6万元左右（包含住院及其他费用）

**结肠**
结肠手术全部费用约为11万到12万元左右（包含住院及其他费用）

**皮瓣**
皮瓣手术全部费用忘记咨询（包含住院及其他费用）

## 挂号

暨南大学附属第一医院（广州华侨医院）微信公众号，选择暨大总院→外科→整形美容科→整形美容外科门诊

**Comment by septs** [comment]
@Chiaki2333 请使用模版提交 https://github.com/mtf-wiki/MtF-Wiki/issues/new?assignees=&labels=psyco&template=psyco.yml

**Comment by septs** [comment]
我重新检查下

**Comment by Chiaki2333** [comment]
上面的信息都是昨天（2022年2月8日）到院咨询拿到的。“易性症”的说法是护士发的一张图片上写的。

**Comment by Rinfair-CSP-A016** [comment]
请等待双向确认后处理
