### ISSUE TITLE
杭州｜来建波

### ISSUE THREAD

**Issue by tuboshufps** [mtf-wiki/MtF-Wiki#326]
### 医院名称

浙江大学医学院附属第一医院（庆春院区）

### 医生姓名

来建波

### 标签

初诊获得证明/假条, 无需抢号/挂号

### 注意事项

挂号：
通过「支付宝-医疗健康-（选择城市杭州）-预约挂号-选择浙江大学医学院附属第一医院（庆春院区）-官方挂号平台-精神卫生科（庆春）-精神卫生科门诊（庆春）」进行预约挂号。
因为是普诊挂号，实际可能会遇到不是该医生问诊的情况

挂号费：
工作日15元，节假日17元。（有杭州市医保均-6元）

取号报到：
入院后可直接前往一号楼三楼，在院内任意自助服务机上取号，取号时缴纳挂号费。
取号后在一号楼三楼C区的自助报到机上凭挂号单上的二维码扫码报到。

问诊：
会让你自己说基本的情况，有成为女孩子的想法有多久，什么时候开始意识到之类的。
笔者表明自己已经HRT一百多天后询问焦虑的来源是因为「性别焦虑」还是「HRT所带来的副作用」。出示了所服用的激素药物，但医生貌似不看。
笔者表示家长对性别重置手术的同意与支持后会在病例中加入「诉家属已知情」字样。独自前往也不用打电话证明。
然后询问今天来此想要获得什么帮助，笔者回答获得证明用于性别重置手术。
医生会问想要在国内还是国外进行性别重置手术。然后多次劝说对手术要慎重，自己对自己的身体负责。
之后就是给病例+开证。

（吐槽：浙一作为浙江省最好的公立医院居然还在用ICD-10，你浙这个共同富裕示范区到底行不行鸭）

后续：
开出来的证明记得去同一楼层的综合服务中心敲公章，病例也可以敲一下，反正不敲白不敲。

（220520）获得证明后可在同一医院内分泌科的董凤芹医生处获得补佳乐（机打）、爱斯妥与色谱龙（手写）的处方。董医生对易性症熟悉，且获得处方无需进行任何检查。

（220520）笔者之后因SRS办理护照需要，提出能否将证明的“处理意见”栏修改成“行外科手术治疗”，院方遂将“处理意见”栏改为“患者要求行外科手术治疗”，并获得一份新的证明。

对editor的备注：以上内容对该医生的普适性存在疑问。**建议考虑放弃此医生。**
（因为当时貌似这医生急着去做定期的核酸检查，所以变成了 一次过+0量表+无需证明家长支持+5分钟光速开证）

（220520）对editor的备注2：笔者之后前往浙一复诊多次，该医生认可初诊时所开的证明，且同科室其他医生也认可该医生在初诊时开出的证明。但仍然需要更多信息补充以消除备注1所提出的问题。

### 证明样式

email send to mtf@kuaer.club

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by septs** [comment]
本 issue 将长期维持打开状态，等待后续报告

**Comment by Rinfair-CSP-A016** [comment]
由于目前报告资料较少，将搁置留观

**Comment by septs** [comment]
由于长时间未跟进，请在重新确认后 reopen 本 issue
