### ISSUE TITLE
在汉语语境下，价格不适合使用 k 缩略

### ISSUE THREAD

**Issue by saeziae** [mtf-wiki/MtF-Wiki#358]

**Comment by septs** [comment]
<img width="957" alt="CleanShot 2022-02-12 at 20 17 39@2x" src="https://user-images.githubusercontent.com/3842474/153710976-29e5807f-306a-410c-a99c-a440e4d8a4be.png">

<https://zh.wikipedia.org/zh-cn/%E5%8D%81%E8%BF%9B%E5%88%B6#%E6%96%B9%E6%B3%95>

十进制词头真的合适吗？

**Comment by saeziae** [comment]
> <img alt="CleanShot 2022-02-12 at 20 17 39@2x" width="957" src="https://user-images.githubusercontent.com/3842474/153710976-29e5807f-306a-410c-a99c-a440e4d8a4be.png">
> 
> https://zh.wikipedia.org/zh-cn/%E5%8D%81%E8%BF%9B%E5%88%B6#%E6%96%B9%E6%B3%95
> 
> 十进制词头真的合适吗？

I mean 汉语一般都是缩略成 5 万而不是 50k，或者就直接 50000 也比 50k 更正常一点

**Comment by Cryolitia** [comment]
建议使用 https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat 避免一切争论（有事出门左转找W3C吵去）
