### ISSUE TITLE
对SRS大项中 "金融账户变更指引" 条目消失的疑问

### ISSUE THREAD

**Issue by azmmmm** [mtf-wiki/MtF-Wiki#368]
请问这个条目是删除了吗，我查询history搜索finan、financial、fi、delete....都未找到相应记录。 
个人觉得这个条目对于术后变更信息还是有一定指导意义的。

**Comment by septs** [comment]
https://github.com/mtf-wiki/MtF-Wiki/commit/47f54928bbf1e9a530dc20b146423aafdf037f4d#diff-e2d53a3dc4bd03106549efdfeb01354e994aefc5bbc97bacb6b656777f0c4884

**Comment by saeziae** [comment]
银行、手机卡、各种账户，都可以用证件变更证明和新身份证更改，不必特别冗余列出。

**Comment by azmmmm** [comment]
理解，感谢回复。
