### ISSUE TITLE
广东省人民医院姜美俊医生初诊情况

### ISSUE THREAD

**Issue by exitance** [mtf-wiki/MtF-wiki#374]
### 医院名称

广东省人民医院

### 医生姓名

姜美俊

### 标签

LGBT+ 友善, 观察期/随访, 需要家长介入

### 注意事项

姜医生会询问：

- 来看医生的目的，什么时候开始认为自己是跨性别者，有什么具体表现；
- 如果带家长，会询问家长的态度（不知道这个是否影响开证）以及养育方式；
- 在哪里上学，什么学校；
- 开证明用来做什么

需要做的检查：

- 心理测试（电脑自测加收 50％）：
  - 明尼苏达多相个性测试；
  - 症状自评量表；
  - 简明精神病评定量表（BPRS)；
  - 父母养育方式评价量表（EMBU）；
- 外周血染色体检查

回答家长的问题：

- 我爸的问题：跨性别是否有程度之分（他说在北同家长群看到一些人反应比较激烈）；
- 姜医生的回答：跨性别只有是和不是之分，反应激烈是不同人处理事情的方式和性格不一样（原话）

其它：

- 开证明需要一年的观察期，一年后复诊对于性别认同无变化可以开证明；
- 年龄好像有要求，初诊时 19 岁被说太小；
- 友跨，说可以尝试去北京上海等地进行 hrt

关于我自己的情况：

- 家长态度支持；
- 没有激素和手术，外表着装比较接近男性（ftm），但非天赋党；
- 结果没有抑郁和其它精神心理上的问题

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Rinfair-CSP-A016** [comment]
是否可以提供正式开具证明前的病历或其它材料证明**此医生确实有开证资质**以及**此医生的证可以用于HRT和SRS（最好）**
