### ISSUE TITLE
南京脑科医院武欣医生初诊情况

### ISSUE THREAD

**Issue by exitance** [mtf-wiki/MtF-Wiki#375]
### 医院名称

南京脑科医院

### 医生姓名

武欣

### 标签

LGBT+ 友善, 初诊获得证明/假条, 需要介绍信

### 注意事项

费用：

- 挂号 35 块，初次到南京脑科医院就诊加收 39 块；
- 心理测试 273 块

医生会询问：

- 什么时候开始有性别认同的意识，有什么具体表现；
- 如果带家长，会询问家长的态度（不知道这个是否影响开证）；
- 开证明需要用来做什么

需要做的检查：

- MMPI、还有一个似乎是人格测试的表、三个测抑郁焦虑的表（即使之前在别的医院做过也需要重新做一遍）

其它：

- **介绍信**，没有介绍信只能开诊疗联系单不能开诊断证明，介绍信要留存在医院；
- 友跨，开证之前会问做好激素和手术的准备了吗；
- 号很好抢，放号当天内都可以抢到

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by septs** [comment]
如果未获得诊断证明，只能添加到未确认列表。

**Comment by saeziae** [comment]
> 如果未获得诊断证明，只能添加到未确认列表。

个人认为可以正式收录。南京脑科医院是必须有介绍信才给证明的，医生说能开应该就没有问题。p.s. 我好像见过有人拿的这位医生的证明。

**Comment by ddzzkunye** [comment]
哈喽, 他在哪个科室啊, 为啥我查到的他在失眠专科  
![南京脑科医院小程序](https://github.com/project-trans/MtF-wiki/assets/92249100/9e953f59-469e-4148-ad6b-4dc8932e0cb5)  
截图是南京脑科医院小程序

**Comment by BeiyanYunyi** [comment]
> 他在哪个科室啊, 为啥我查到的他在失眠专科

嗯，是失眠科没错

**Comment by ddzzkunye** [comment]
> 嗯，是失眠科没错

大佬去过啊, ,  
wiki里没有表现是失眠科室哎, 要不要考虑加一下?

**Comment by BeiyanYunyi** [comment]
> wiki里没有表现是失眠科室哎, 要不要考虑加一下?

感谢建议。已提出 #1027 。
