### ISSUE TITLE
贵州省人民医院 吴勇

### ISSUE THREAD

**Issue by mis1042** [mtf-wiki/MtF-Wiki#388]
### 医院名称

贵州省人民医院

### 医生姓名

吴勇

### 标签

LGBT+ 友善, 初诊获得证明/假条

### 注意事项

见Pull Requests内容

### 证明样式

![-60c76244262bc3c2](https://user-images.githubusercontent.com/53249654/155869207-eb71e51b-4748-4f1b-bfc6-a050d1d57d53.jpg)

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by mis1042** [comment]
#387

**Comment by saeziae** [comment]
#387 merged
