### ISSUE TITLE
广州市第一人民医院精神-临床心理门诊徐丽敏初诊情况

### ISSUE THREAD

**Issue by kobayakawa-yuki** [mtf-wiki/MtF-Wiki#392]
### 医院名称

广州市第一人民医院（盘福路院区）

### 医生姓名

徐丽敏

### 标签

LGBT+ 友善, 初诊获得证明/假条

### 注意事项

关于挂号：小程序“广州市第一人民医院”挂号，徐医生每周四上午出诊
关于初诊：初诊需在门诊护士站报到，填写心理问卷（217元，如开具价格80元的“首诊心理检查”，此项收费为非必需项目， 可与医生护士协商退款）
关于就诊：非常友跨。两位姐妹同日初诊，均在不需家长参与情况下完成开证

### 证明样式

![Uploading IMG20220303130308.jpg…]()

### 以 CC-BY-SA 4.0 协议分发

- [x] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by septs** [comment]
@kobayakawa-yuki 请重新更新”证明样式“

**Comment by ltghw** [comment]
> @kobayakawa-yuki 请重新更新”证明样式“
@septs 
已有其他人补充了证明样式，建议关闭此issue
