### ISSUE TITLE
MtF or MTF?

### ISSUE THREAD

**Issue by Officeyutong** [mtf-wiki/MtF-Wiki#4]
项目仓库和Logo里写的是MtF，而正文却是MTF，所以到底以哪个为准呢（x

**Comment by ayalhw** [comment]
缩写的话我记得两个都可以，MtF 是因为 to 是副词，一般首字母小写

**Comment by Officeyutong** [comment]
> 缩写的话我记得两个都可以，MtF 是因为 to 是副词，一般首字母小写

一会MtF一会MTF的话会不会有点不美观x
