### ISSUE TITLE
建议补充英语四六级和各种专业证书的性别相关信息修改流程

### ISSUE THREAD

**Issue by caihongxianzi** [mtf-wiki/MtF-Wiki#400]
性别相关信息包括性别、身份证号、姓名、照片等。
这些证书对MtF（尤其是某些专业的MtF）的升学和就业很重要，然而网上这方面的资料很少。至少我没有找到四六级的修改流程。

**Comment by saeziae** [comment]
原则上都可凭 公民身份证号码更正证明 和 新身份证 进行更改[^1]，建议咨询学校教务或发证部门。

本人将于修改身份证后去尝试四六级证书的相关修改。也欢迎其他姐妹探索信息。

[^1]: [证件变更指引](https://mtf.wiki/zh-cn/docs/srs/id-card/#%e5%8f%98%e6%9b%b4%e5%90%84%e7%b1%bb%e8%af%81%e4%bb%b6%e5%92%8c%e8%b4%a6%e6%88%b7)

**Comment by caihongxianzi** [comment]
> 原则上都可凭 公民身份证号码更正证明 和 新身份证 进行更改[1](#user-content-fn-1-534b35cc57f24d5fba4ad019e764a319)，建议咨询学校教务或发证部门。
> 
> 本人将于修改身份证后去尝试四六级证书的相关修改。也欢迎其他姐妹探索信息。
> 
> ## Footnotes
> 1. [证件变更指引](https://mtf.wiki/zh-cn/docs/srs/id-card/#%e5%8f%98%e6%9b%b4%e5%90%84%e7%b1%bb%e8%af%81%e4%bb%b6%e5%92%8c%e8%b4%a6%e6%88%b7) [leftwards_arrow_with_hook](#user-content-fnref-1-534b35cc57f24d5fba4ad019e764a319)

原则上可改，但和身份证不同，这些证书的修改似乎没有专门的法律规定，实践中很可能存在学校教务或发证部门拒绝修改的情况，这种情况下MtF往往维权无门。

**Comment by Rinfair-CSP-A016** [comment]
一般来说这类考试只需要直接提交有关证明材料至教育考试院进行复核与信息更改（与学历更改流程基本一致）

**Comment by caihongxianzi** [comment]
> 一般来说这类考试只需要直接提交有关证明材料至教育考试院进行复核与信息更改（与学历更改流程基本一致）

现在学历更改还是不能保证成功，很大程度上取决于学校的态度。这类考试应该也是如此。

**Comment by cocoAutumn** [comment]
![mmexport1647099275351](https://user-images.githubusercontent.com/88474935/158047277-5b020845-247d-46bd-b42d-3b36c975869c.png)
limelight有人问我这种“读研期间srs”的，本/专科学历和学士学位还需要改么，怎么改？

**Comment by saeziae** [comment]
毕业之后难改学历是现状事实。
鉴于某些单位在招聘时会查看本科学历，应该结合个人的人生规划实际来决定是否要赶在本科毕业前修改。
顺祝文祺

**Comment by septs** [comment]
考虑到近些年来多起与 学历造假 相关的 新闻 与 公职人员 被处置的力度
变更学历难度 并不来自现行 法规限制，更多为 行政层面 的 约束

因此此话题并不具备 实行层面 的意义

目前具备可行性选项仅为 毕业前修改学历、重修学历、海外学历变更

**Comment by caihongxianzi** [comment]
> 原则上都可凭 公民身份证号码更正证明 和 新身份证 进行更改[1](#user-content-fn-1-d9ee3f1fbedecb34b171687862be47fd)，建议咨询学校教务或发证部门。
> 
> 本人将于修改身份证后去尝试四六级证书的相关修改。也欢迎其他姐妹探索信息。
> 
> ## Footnotes
> 1. [证件变更指引](https://mtf.wiki/zh-cn/docs/srs/id-card/#%e5%8f%98%e6%9b%b4%e5%90%84%e7%b1%bb%e8%af%81%e4%bb%b6%e5%92%8c%e8%b4%a6%e6%88%b7) [leftwards_arrow_with_hook](#user-content-fnref-1-d9ee3f1fbedecb34b171687862be47fd)

证件变更指引的页面内容已经更新了。用新身份证号重考的话，是不是只能先重考四级，重考的四级过了才能报名重考六级？还是说四级和六级可以在同一次考试中重考？休学期间能否报考英语四六级？

**Comment by saeziae** [comment]
> 证件变更指引的页面内容已经更新了。用新身份证号重考的话，是不是只能先重考四级，重考的四级过了才能报名重考六级？还是说四级和六级可以在同一次考试中重考？休学期间能否报考英语四六级？

已实践。已考四级可以直接考六级。
系统会提示查不到四级成绩，然后有填写四级准考证编号的窗口，填了会提示身份证号不同，需要申请复核，然后找学校相关老师人工通过。
