### ISSUE TITLE
你好~！我有意向增加mtf.wiki国内备案镜像站

### ISSUE THREAD

**Issue by xlch88** [mtf-wiki/MtF-Wiki#410]
大概会使用wiki.qwq.pink这个域名，使用的是企业备案，完全公益并且全量同步不修改新增任何内容（但是出于国内合规考虑，会在底部增加备案号）。
本人也是mtf一只~
请问一下站方是否能接受这个请求呢？

**Comment by septs** [comment]
基于 SEO 的原因除 MtF.wiki 以外的域名均不能产生收录记录
避免被搜索引擎以 站群/内容农场 原因予以降级处置

**Comment by septs** [comment]
其他方面意见请等待 @saeziae

**Comment by Rinfair-CSP-A016** [comment]
目前受国内大环境影响暂时不接纳国内服务器的**备案**镜像站，以防被一条链钓鱼。当然还是感谢你的建议！

**Comment by saeziae** [comment]
> 基于 SEO 的原因除 MtF.wiki 以外的域名均不能产生收录记录 避免被搜索引擎以 站群/内容农场 原因予以降级处置

是否可以该域名特供境内搜索引擎？而对 google 之类不引索？

> ……以防被一条链钓鱼。

是否可以套壳其他名称？比如用纯中文写【跨性别女性百科】之类的

**Comment by undefined-moe** [comment]
robots.txt 可以只限制 googlebot

**Comment by xlch88** [comment]
所以还是没探讨出什么结果嘛>_<

**Comment by xlch88** [comment]
大概的想法：
1.加备案号
2.添加一段说明，大概意思是：这个是mtf.wiki镜像站 ；除非不可抗力否则会尽可能维持正常运行；缓存时间大概30min；会指向原站mtf.wiki；
3.robots.txt屏蔽google bing等国外搜索引擎，仅让国内搜索引擎蜘蛛检索。

**Comment by saeziae** [comment]
请向我(<i@estela.cn>)私信你的QQ账号，我会跟进具体落实事宜。
