### ISSUE TITLE
云南大学附属人民医院（云南省第三人民医院）

### ISSUE THREAD

**Issue by Wu-XR** [mtf-wiki/MtF-Wiki#422]
### 医院名称

云南大学附属人民医院（云南省第三人民医院）

### 医生姓名

不是我去开所以未知（我是被委托代填写）

### 可开具的药品

戊酸雌二醇, 醋酸环丙孕酮

### 注意事项

**据朋友和像萨拉锉加一类人的描述，只需要通过这一个医生就可以进行诊断**
_但是云南省本身对跨性别的态度几乎可以说很不友好，请从外地赶来开完的朋友立刻走人，千万不要出昆明（呈贡可以去），也不要去西山之类的地方（除非你是深柜），该医院存在部分医生恐跨情况，被路人说人妖也是很正常的事情。_
该医生开具的证明上面可能就是固定的_**厌恶自己生理性别（多少）年**_之类的。

### 以 CC-BY-SA 4.0 协议分发

- [x] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Rinfair-CSP-A016** [comment]
请提供有关的病历和证明材料，并明确开证的资料和问诊流程
