### ISSUE TITLE
有无必要设置中小学校园指南板块？

### ISSUE THREAD

**Issue by caihongxianzi** [mtf-wiki/MtF-Wiki#424]
《2017中国跨性别群体生存现状调查报告》显示，中小学对MTF而言非常艰辛。我觉得可以考虑设置中小学校园指南板块。

**Comment by Aleksanaa** [comment]
可是能做什么呢？确实有少数贵族学校对mtf的待遇还可以，但是让他们不仅要去那里还要过得好的难度等于重新投胎...

**Comment by Dringsim** [comment]
能收集到信息吗？
可靠的信息个人认为都可以收录（ ）
不过排雷什么的……中小学选择空间不大吧（即使成绩优异）🤔

**Comment by saeziae** [comment]
> 至少可以列举一些对MTF不友好的学校，帮助MTF学妹们排雷

激进一点可以认为中小学几乎都不友好……

**Comment by cocoAutumn** [comment]
中小学指南可能没有必要“具体到学校名称”而只能和mtf.party一样讲一些通用的手段了（短假发什么的）

**Comment by Aleksanaa** [comment]
比如，“在学习上单方面碾压其他同学，以获得老师的支持，也不用考虑其他同学的看法”
虽然听起来很荒谬，但是它工作。

**Comment by caihongxianzi** [comment]
> 比如，“在学习上单方面碾压其他同学，以获得老师的支持，也不用考虑其他同学的看法” 虽然听起来很荒谬，但是它工作。

可在某些校规面前还是工作不了…我初中在学习上能碾压年级绝大部分同学，最后考上了全省份最好的重点高中。但还是过得无比黑暗，照样会被骂“一点男子汉的样子都没有” ，屡次因仪容仪表不合格遭受各种残酷的惩罚，还总是被一群不学习的混子们霸凌…所以我真的特别同情那些辍学的MTF姐妹

**Comment by caihongxianzi** [comment]
> > 至少可以列举一些对MTF不友好的学校，帮助MTF学妹们排雷
> 
> 激进一点可以认为中小学几乎都不友好……

那也可以设立板块，让学妹们具体了解一下哪些学校在哪些方面对MTF不友好

**Comment by septs** [comment]
1. 钱从哪里来？
2. 择校权在谁手上？

**Comment by Rinfair-CSP-A016** [comment]
首先全国中小学数量巨大远超过大学，因此几乎不可能对中小学分学校进行板块讨论
我们只能从广泛的要求入手，分析普遍的中小学反跨、少数私立/贵族学校友跨的情况。
但是实际上当时他们作为学生，对学校是没有选择权的，只有有钱的家长（这类多数是家长党）才会选择将孩子送到少数学校避免反跨性孤立。因此开设这个板块没有意义，也对整个大群体没有什么帮助

**Comment by caihongxianzi** [comment]
> 1. 钱从哪里来？
> 2. 择校权在谁手上？

中考报志愿的时候学生还是有一定择校权的

**Comment by saeziae** [comment]
> 中考报志愿的时候学生还是有一定择校权的

![QQ图片20220322114733](https://user-images.githubusercontent.com/26759054/159404138-3a1b9594-c2c9-464f-bca5-8c4dddf13f02.jpg)

**Comment by Rinfair-CSP-A016** [comment]
> > 1. 钱从哪里来？
> > 2. 择校权在谁手上？
> 
> 中考报志愿的时候学生还是有一定择校权的

可是你有那么多钱选不反跨的学校吗？

**Comment by shinohara-rin** [comment]
对此担心可能会更容易被某些奇葩家长之类的人找事

反手给你打一个诱导未成年人变性（already

**Comment by Dringsim** [comment]
> 中考报志愿的时候学生还是有一定择校权的

很难出市吧（ ）

**Comment by cocoAutumn** [comment]
> > 中考报志愿的时候学生还是有一定择校权的
> 
> 很难出市吧（ ）

确实是个问题，出市基本意味着住校或者（如果是从小县城到地级市或者从地级市到省会）家长陪读，各有各的麻烦……

**Comment by caihongxianzi** [comment]
> 首先全国中小学数量巨大远超过大学，因此几乎不可能对中小学分学校进行板块讨论 我们只能从广泛的要求入手，分析普遍的中小学反跨、少数私立/贵族学校友跨的情况。 但是实际上当时他们作为学生，对学校是没有选择权的，只有有钱的家长（这类多数是家长党）才会选择将孩子送到少数学校避免反跨性孤立。因此开设这个板块没有意义，也对整个大群体没有什么帮助



> 对此担心可能会更容易被某些奇葩家长之类的人找事
> 
> 反手给你打一个诱导未成年人变性（already

那我该如何帮助MTF学妹们，避免她们像我一样沦为“校暴党”呢？

**Comment by cocoAutumn** [comment]
[指派两性在校园暴力中的双标认定](https://limelight.moe/t/topic/6744)
难蚌。
![image](https://user-images.githubusercontent.com/88474935/159421350-629b9175-9038-42b3-87bf-0d6ff0706259.png)

**Comment by caihongxianzi** [comment]
> 首先全国中小学数量巨大远超过大学，因此几乎不可能对中小学分学校进行板块讨论 我们只能从广泛的要求入手，分析普遍的中小学反跨、少数私立/贵族学校友跨的情况。 但是实际上当时他们作为学生，对学校是没有选择权的，只有有钱的家长（这类多数是家长党）才会选择将孩子送到少数学校避免反跨性孤立。因此开设这个板块没有意义，也对整个大群体没有什么帮助



> [指派两性在校园暴力中的双标认定](https://limelight.moe/t/topic/6744) 难蚌。 ![image](https://user-images.githubusercontent.com/88474935/159421350-629b9175-9038-42b3-87bf-0d6ff0706259.png)

私立学校也有对MTF非常不友好的。我中小学都是在偏远地区上的，那里非常保守，当地教育厅印发的《中学生日常行为规范》中明确写明了“男生不留长发”。我初中上的就是私立学校，学校对仪容仪表的要求特别严格，导致我过得非常艰难。

**Comment by Dringsim** [comment]
> 当地教育厅印发的《中学生日常行为规范》

插一句，《中学生日常行为规范》（教基[2004]6号附件3）是教育部发布的

**Comment by septs** [comment]
就目前来看对“学校管理规章制度”的“违宪审查”属于不可期事件，故该问题基本无解。

see https://zh.wikipedia.org/zh-cn/违宪审查#中華人民共和國
see 民法典人格权编

**Comment by caihongxianzi** [comment]
> > 当地教育厅印发的《中学生日常行为规范》
> 
> 插一句，《中学生日常行为规范》（教基[2004]6号附件3）是教育部发布的

确实，不过有些省份也发布了《XX省（市、自治区）中学生日常行为规范》

**Comment by Wu-XR** [comment]
还有就是依据亚佐夫讲的，有些学校的校园欺凌还会给被欺凌者投放雌二醇来制造跨性别者（我不清楚药哪儿来的，但是我见过这方面的所有过程，包括她们的医学检查报告），请问这种恶劣情况又该怎么界定？

**Comment by Wu-XR** [comment]
> > 首先全国中小学数量巨大远超过大学，因此几乎不可能对中小学分学校进行板块讨论 我们只能从广泛的要求入手，分析普遍的中小学反跨、少数私立/贵族学校友跨的情况。 但是实际上当时他们作为学生，对学校是没有选择权的，只有有钱的家长（这类多数是家长党）才会选择将孩子送到少数学校避免反跨性孤立。因此开设这个板块没有意义，也对整个大群体没有什么帮助
> 
> > 对此担心可能会更容易被某些奇葩家长之类的人找事
> > 反手给你打一个诱导未成年人变性（already
> 
> 那我该如何帮助MTF学妹们，避免她们像我一样沦为“校暴党”呢？

亚佐夫和一些人是校暴被跨性别，这估计不止校暴那么简单，她现在燥郁症非常严重（小学给她投药的人现在又跟她在一个班，还逼着她出柜）

**Comment by Wu-XR** [comment]
<s>如果各位觉得有必要的话，我以后会上传一下亚佐夫的情况，可能有些意料之外的事情，做好准备。</s>
中小学情况远比你们预期的要糟糕。

**Comment by Aleksanaa** [comment]
> 还有就是依据亚佐夫讲的，有些学校的校园欺凌还会给被欺凌者投放雌二醇来制造跨性别者（我不清楚药哪儿来的，但是我见过这方面的所有过程，包括她们的医学检查报告），请问这种恶劣情况又该怎么界定？

来源请求

**Comment by saeziae** [comment]
开设板块的前提有是内容。如有人会写这方面内容，欢迎另开issue或pr. 相关讨论请移步limelight

**Comment by cocoAutumn** [comment]
https://github.com/mtf-wiki/MtF-Wiki/issues/451
https://limelight.moe/t/topic/10546
现在有内容了，我们至少知道#451中的这所高中即使有诊断证明+hrt+rle也不许留长发只能退学，而同样在长沙的雅礼和另一所则可以。
