### ISSUE TITLE
文档管理模板问题

### ISSUE THREAD

**Issue by Wu-XR** [mtf-wiki/MtF-Wiki#428]
之前一直在fandom工作，不清楚GitHub的情况，感觉现在条目归类都要手动，很难想象以后如果大规模建设需要多少手操……
一般是Template式的这种，我比较习惯套用信息框（你们可以从后面看源码）
<table style="font-size: 95%; width: 75%; margin: 0 auto -2px auto; box-shadow:0 1px 2px 0 rgba(0,0,0,.14),0 1px 5px 0 rgba(0,0,0,.12),0 2px 1px -2px rgba(0,0,0,.2); border: 1px #AAA solid; border-left: 10px solid #228b22; border-collapse: collapse; background-color: snow; color: #000; border-left: 10px solid （边框色）;" class="plainlinks">
<tr>
<td style="width: 55px; padding: 2px; text-align: center;border-right:1px solid #AAA;">（图片）</td>
<td style="padding: 5px 20px;"><b>（题目）</b>
<div style="font-size: smaller; margin:2px 0px 2px 25px;">
<p>这是一个信息框！</p></div></td></tr></table>
 ![Screenshot_20220325_234527_edit_2134135538896](https://user-images.githubusercontent.com/76834320/160154369-272aec9d-efd9-4b5c-96bf-2f0934ad3548.jpg)

这个是Fandom效果，然后可以套[[category:类别]]进行Template的固定，之后只需要直接插入Template就可以了。
自然，这只是基于Mediawiki的情况，不知道此地可不可行

**Comment by Rinfair-CSP-A016** [comment]
由于zdoc的限制可能没有办法套模板固定（这在一定方面也和GitHub本身有关系）
不过后续如果有重构计划的话我们会考虑你的建议，谢谢！

**Comment by Wu-XR** [comment]
谢谢，等到以后Mediawiki建构全面引入的话我会来的！
