### ISSUE TITLE
贵州省人民医院吴勇医生处疑似需要携带家长陪同就诊

### ISSUE THREAD

**Issue by HalfSweet** [mtf-wiki/MtF-Wiki#432]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/southwest/wu-yong/

### 内容

该医生疑似需要携带家长陪同就诊，今日前往就诊的时候医生表示需要家长知情且陪同前往就诊才可进行检查诊断。暂不清楚是否为普遍现象

**Comment by mis1042** [comment]
您好，这个信息是我提供的，我前往该医院是有父母陪同的，但是医生全程没有提及父母，甚至没有问父母有没有来

**Comment by HalfSweet** [comment]
但是今天我前往的时候医生询问父母是否知情后便要求需要携带父母且陪同就诊才能进行诊断，不大清楚是修改规则了还是仅仅只是个例（

**Comment by mis1042** [comment]
这个暂不清楚，我当时去的时候第一个挂的号是向慧医生，但是她不开（包括门诊病历）然后外加家长那边不太支持，~~直接心理科门口炸抑郁准备自杀~~，然后早上完了向慧医生走了，下午是吴勇医生，他直接就询问了一下检查了一下就开了

**Comment by HalfSweet** [comment]
所以感觉还是把不需要家长陪同的tag去掉比较好？毕竟现在看起来也不一定是完全不需要的（

**Comment by mis1042** [comment]
可以，这就修改
