### ISSUE TITLE
建议mtf.wiki校园指南中补充：该校是否存在毕业后修改文凭中性别相关信息的先例

### ISSUE THREAD

**Issue by caihongxianzi** [mtf-wiki/MtF-Wiki#443]
时至今日，文凭中性别相关信息的修改依然无法保证成功。《跨性别证件修改手册》中提到，能否修改文凭中性别相关信息，主要取决于学校的态度。因此，我觉得补充这一点意义重大，虽然先例不多，但确实能为在校期间无法SRS的MTF（比如正在上大三，即将面临读研院校选择的我）指明方向。

> 愿今后所有的跨性别少年都能安心考学，不要再想着“考上了也没有用，反正做了手术就不能拿出来了”；
> 愿今后所有的跨性别学子都能安心求学，不要再担心“毕业之后就不能改了，现在被同学欺负也就这几年，忍忍也就罢了”；
> 愿今后所有的跨性别职场人士都能找到与自己能力相匹配的工作，不要再焦虑“手术之后我就是个新人，从零开始奋斗”。

**Comment by tuboshufps** [comment]
可能存在时效性，普适性，广泛性问题。例：“先前通过，后因环境/政策恶化，无法通过” ，“因学生与该学校‘关系较好’，故学校协助办理。”或“案例过少，只有极个别学校能补充先例”等情况。
（imho 需要推动相关政策在该类事宜上的关联性，例：修改身份证性别则自动修改学历性别。而不是”取决于学校的态度“。）
FYI to editor, thx

**Comment by caihongxianzi** [comment]
> 可能存在时效性，普适性，广泛性问题。例：“先前通过，后因环境/政策恶化，无法通过” ，“因学生与该学校‘关系较好’，故学校协助办理。”或“案例过少，只有极个别学校能补充先例”等情况。 （imho 需要推动相关政策在该类事宜上的关联性，例：修改身份证性别则自动修改学历性别。而不是”取决于学校的态度“。） FYI to editor, thx

根据《跨性别证件修改手册》，案例应该还是有一定数量的，只是不清楚学校的具体分布情况。
https://limelight.moe/t/topic/10521/5?u=彩虹仙子

**Comment by saeziae** [comment]
9ff520219e00fa8a6053f7eafd8fe5a907c37a51 已经在贡献者指南之校园指南撰稿要素中添加该要素
