### ISSUE TITLE
上海健康医学院

### ISSUE THREAD

**Issue by yuyikai** [mtf-wiki/MtF-Wiki#449]
### 学校名称

上海健康医学院

### 地址位置

位于浦东新区周浦镇周祝公路279号

### 宿舍独立卫浴

学生宿舍无独立卫生间，均为公共澡堂，公共澡堂就是坦诚相见哈哈哈

### 教学区第三卫生间

只有部分教学楼有，且不一定会开放（很多都是放拖把的）

### 军训减免

不清楚，但军训划水就可以了，累了的话就和教官说，可以到边上休息

### 军训管不管头发

不管

### 体育减免

不清楚

### 医保的可用情况

不清楚，但学生是用大学生医保的，具体的可以参考上海大学生医保的规定

### 校医院可用度

无法激素检查，只能到附近的附属周浦医院检查。疫情期间俺因为买不到药，校医院给我开了补佳乐，所以，应该是可以开到激素药的

### 现状梗概

交通：位于城郊，进城交通大概要一个小时起步；到附近的万达、小上海，大概二十到三十分钟；到附属周浦医院大概十分钟，但下车后走路大概要走十五分钟，附属医院可以做激素六项，但无法做染色体（截至2022年三月）

寝室：南苑分为五人间和三人间，其他校区也大差不差，总体来说都是三人、四人、五人间，无单间（除了隔离宿舍，是单间【为什么我会知道呢，我就在隔离ing，哀~】）寝管不会管学生着装打扮、头发之类的，也不会有异样的眼光。而且只要pass过寝管和其他女生的眼睛，也可以去女寝找同学玩（没错，就是我哈哈哈哈）

校园环境：目前俺学校，从建校到现在只有我一个和学校部分领导老师出柜的mtf，哀~，但总体环境还是很好的。也许是因为学校要建设知名度，所以校内氛围还是很宽松包容的。疫情期间俺药不够了，也会想尽办法帮助我，还是挺友好的。

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by ArtsEpiphany** [comment]
感谢投稿！如果相关信息未来发生变动，欢迎来稿更新。如果您愿意，也可以直接提交pull request。

另外，如果您发现您所在的院系或其他院系对MtF友好或不友好（不同院系的氛围可能差异较大），欢迎投稿新增“院系探路”栏目，这也许能够为MtF选择专业提供帮助。
