### ISSUE TITLE
长沙|陈晋东

### ISSUE THREAD

**Issue by xbscn** [mtf-wiki/MtF-Wiki#462]
### 医院名称

中南大学湘雅二医院

### 医生姓名

陈晋东

### 标签

LGBT+ 友善, 观察期/随访, 初诊获得证明/假条, 需要家长介入

### 注意事项

通过 长沙安肯心理诊所院外门诊
本人是家长党，单人未尝试
费用初诊1200元，复诊1000元

刚开始他会问你一些基本问题，如是否真正想变成女生，是否讨厌第二性征等
笔者提出开青春期阻断剂，医生表示需要经过心理治疗无效后方可开药
给笔者开了拉莫三嗪，并加大原有药量（笔者原有轻狂燥，服用碳酸锂，阿利哌唑，盐酸苯海索）
表示可以开证，但是因为在诊所，需要有时间到湘雅附二去开证
医生在就诊过程中会与家长详细沟通并提出意见

### 以 CC-BY-SA 4.0 协议分发

- [x] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by saeziae** [comment]
待补充在湘雅附二挂号就诊的情况。

**Comment by xbscn** [comment]
开证成功。
未挂号（之前有说）
在湘雅附二找个陈医生空闲的时候进去，有家长陪同
![s](https://user-images.githubusercontent.com/103890529/168470847-2d9dc13b-e817-48eb-801a-0a935c08bc2e.jpg)

**Comment by rainlin233** [comment]
Ummm...性别认同障碍这种证已经失去时效性了，大多数可以的hrt医院都不认了，可以srs的医院就更不用说了，2022年srs标准证是只有：易性症，性别烦躁，性别不一致才能srs

**Comment by septs** [comment]
@xbscn 需要证实可以用于 HRT 治疗，如果无法用于 HRT 治疗那么将缺乏实用价值，谢谢

**Comment by Wu-XR** [comment]
> Ummm...性别认同障碍这种证已经失去时效性了，大多数可以的hrt医院都不认了，可以srs的医院就更不用说了，2022年srs标准证是只有：易性症，性别烦躁，性别不一致才能srs

之前卫建委好像有意向改回认同障碍，尚待观察吧

**Comment by septs** [comment]
由于缺乏后续跟进，因此将本 issue 关闭待后续回复
