### ISSUE TITLE
HRT对脚码与肩宽的影响的疑问

### ISSUE THREAD

**Issue by ljtjerry** [mtf-wiki/MtF-Wiki#473]
在日常聊天中，得知一些mtf在hrt后，（相比HRT前）脚码缩小了1～2码，或者肩宽有所缩小。
在药物／HRT -> HRT 总述 -> HRT效果参考 页面中，感觉最接近的是“肌肉体积、强度降低“和”体脂重新分布”

但是感觉脚和肩部没几块肉。

希望如果有条件的话，能对上述猜想进行确认或者证伪。（就是真的有类似效果，还是只是个人心理作用？）

**Comment by saeziae** [comment]
如果不是心理作用，可能来源于骨量流失，建议检查骨密度。

**Comment by Aleksanaa** [comment]
> 如果不是心理作用，可能来源于骨量流失，建议检查骨密度。

也有可能是“关节间质水分减少”（忘记来源了）？
