### ISSUE TITLE
长沙|张小崔 内容无法访问

### ISSUE THREAD

**Issue by Cryolitia** [mtf-wiki/MtF-Wiki#481]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/midsouth/zhang-xiaocui/

### 内容

该网页中详细信息指向了外链 [limelight.moe/t/topic/6221](https://limelight.moe/t/topic/6221)
但是打开此链接会被重定向至 https://limelight.moe/login
此网站又停止了新用户注册，导致此页内容事实上处于无效状态

建议不要过度依赖其他网站的外链，而是将内容完整搬运过来并在底部注明出处

**Comment by Lhcfl** [comment]
我是该文的原作者，你们可以帮我转载一下（快高考了我没啥时间用github
