### ISSUE TITLE
大连市第七人民医院 (Part 1)

### ISSUE THREAD

**Issue by EK-Source-of-Life** [mtf-wiki/MtF-Wiki#484]
### 医院名称

大连市第七人民医院

### 医生姓名

刘宏

### 注意事项

错误修正 父母关系并不需要公证 如果你催一下，病历和证明当天可取

问诊细节 会问你以后的打算，激素服用多久了，什么时候准备手术，家人的看法，什么时候有想法，然后聊聊天，告诉你你会经历的困难。

注意事项 医生不会主动给你开证明，只会开病历，需要求医生开证明，需要家长一同前往才能开证明，没有家长只能开病历

### 证明样式

![IMG_20220608_211015](https://user-images.githubusercontent.com/107245956/173024840-7cb031ff-e4cc-4f5a-b2ea-34f65d28e8e8.jpg)

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by ArtsEpiphany** [comment]
你好，我们目前收到的信息为，去找同一医院的其他医生开证明可以无需家长。其他内容我们会逐步添加到wiki上，感谢你的贡献。

**Comment by septs** [comment]
建议使用 Microsoft Lens 重新拍摄以便于提供更加舒适的阅读体验

**Comment by septs** [comment]
Duplicate of #498
