### ISSUE TITLE
友情合作中的"Arch木桶饭"QQ群组已不能被搜索到

### ISSUE THREAD

**Issue by LiAlH4qwq** [mtf-wiki/MtF-Wiki#497]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/friendship/

### 内容

如题，目前在QQ已无法再搜索到本群组

**Comment by Fe3O4-Git** [comment]
群组创建者似乎是 https://github.com/starsareintherose （不太确定

**Comment by tuboshufps** [comment]
群还在 群号被ban 搜索了 悲

**Comment by starsareintherose** [comment]
https://matrix.to/#/#arch-mtf:matrix.malacology.net

matrix 可以加和 tg 联通

我 QQ 群因为号被 ban 了一周，得一周后才能看怎么回事

**Comment by Cryolitia** [comment]
所以现在有QQ群或者Terlegram嘛，没用过matrix的喵

**Comment by Fe3O4-Git** [comment]
> 所以现在有QQ群或者Terlegram嘛，没用过matrix的喵
QQ群已经恢复了，telegram群的话有一个但是咱忘掉id了，可以问下 [starsareintherose](https://github.com/starsareintherose) （小声

**Comment by Cryolitia** [comment]
> https://t.me/+vrcKXijzKmU1ZjE1

非常感谢
