### ISSUE TITLE
大连市第七人民医院 (Part 2)

### ISSUE THREAD

**Issue by EK-Source-of-Life** [mtf-wiki/MtF-wiki#498]
### 医院名称

大连市第七人民医院

### 医生姓名

刘宏

### 标签

LGBT+ 友善, 初诊获得证明/假条, 无需抢号/挂号

### 挂号
在大连市第七人民医院微信公众号挂号，会骗走你16块钱
坐诊时间：周一下午和周二上午
号很好挂

### 问诊细节
很友跨，会问你以后的打算，激素服用多久了，什么时候准备手术，家人的看法，什么时候有跨性别想法，什么时候想法最强烈，为什么会这样，个人目前的状态，有没有去其他医院看过，然后聊聊天，告诉你会经历的困难，

### 检查项目
明尼苏达多项个性测验(C类量表)
症状自评量表(C类量表)
艾森格个性测验(C类量表)
脑电图(会给你涂很难洗掉的恶心心的白乎乎的不明非牛顿流体)

### 注意事项
1. 医院一楼服务台(是一楼不是二楼!)会叫你写一个表并骗走你60块钱
2. 复印病历在医院外的档案室内不在医院里面，会骗走你1块钱
3. 打印证明在一楼证明打印处，会骗走你15块钱
4. 做脑电图和量表会骗走你数额不定的钱(PS:xyn的钱真好骗)
5. 医生不会主动给你开证明，只会开病历，需要求医生开证明
6. 如果你催一下，病历和证明当天可取，不催的话病历需要三天后
7. 医生实际上比照片老很多

### 证明样式

病历第一页
![病历第一页扫描件](https://user-images.githubusercontent.com/107245956/174929955-1d0e0af3-b12f-44e7-b84b-5ba51388648c.jpg)

病历第二页
![病历第二页扫描件](https://user-images.githubusercontent.com/107245956/174929944-55905d93-770b-40a6-9434-67f1086870c3.jpg)

诊断证明
![诊断证明扫描件2](https://user-images.githubusercontent.com/107245956/174929940-0d0f355a-8ba5-4d88-8086-ee522d767163.jpg)

### 以 CC-BY-SA 4.0 协议分发

- [x] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by ArtsEpiphany** [comment]
请注意保护你的个人信息，你在这里发布的内容任何人都能看到

**Comment by EK-Source-of-Life** [comment]
> 请注意保护您发布的个人信息安全 您在这里发布的内容，任何人都可以看到

谢谢，我忘记打码了，已修改
