### ISSUE TITLE
安徽医科大学第一附属医院-赵宇

### ISSUE THREAD

**Issue by EK-Source-of-Life** [mtf-wiki/MtF-Wiki#500]
### 医院名称

安徽医科大学第一附属医院

### 医生姓名

赵宇

### 前置条件

1.18岁以上
2.监护人签字同意并公证
3.易性症证明

### 费用构成

无

### 注意事项

注意：缺乏真实案例报告，此消息从同院张贤生处得知

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by septs** [comment]
该情况属于未经证实，可能将收录于未确认列表

https://mtf.wiki/zh-cn/docs/unconfirmed/

**Comment by ArtsEpiphany** [comment]
已添加至未确认列表
