### ISSUE TITLE
四川省精神医学中心李慧已停止开具证明

### ISSUE THREAD

**Issue by NKNaN** [mtf-wiki/MtF-Wiki#504]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/southwest/li-hui

### 内容

6月20日去问诊的时候，李慧医生明确表明自己将不会再开具性身份障碍的医学证明。她一方面认为既然新的国际标准已经去病化，那就没有必要再开疾病证明了，另一方面确实是因为恶意举报让她觉得很为难，问诊当天听说之前又出现了被家长威胁说要举报的情况......很同情李慧医生。她表示虽然自己不会再开证明，但是仍然可以带父母前去沟通，也可以打印性身份障碍的病历。

**Comment by septs** [comment]
建议证实，该病历在川渝地区均可用于 HRT 治疗

**Comment by Aleksanaa** [comment]
可能在一段时间内，非家长陪同前往时，无法打印病历

**Comment by septs** [comment]
希望有人能重新复盘川渝地区目前可用的医疗资源

**Comment by tuboshufps** [comment]
需要川渝地区的药娘骰子（？

**Comment by YukariChiba** [comment]
不只是川渝地区，全国范围内最近均有报告称一些精神科医生在政策上发生变化。Wiki 上的信息会在一定程度上影响将来寻求问诊的姐妹的行程安排，身边亦有数位姐妹被突发的政策变更和过时信息折腾得焦头烂额。

建议从以下几点进行摸排：

- 能否一次开出病历及其条件
- 能否一次开出证明及其条件
- 证明或病历上的名称（性身份障碍/易性症/性别不一致 等）
- 是否存在观察期，观察期期限
- 家长陪同是否能够改变上述条件
- 年龄满/未满18岁是否能够改变上述条件
- 其它因素是否能够改变上述条件（女性化外表/RLE 等）
- 开出的病历可用于？
- 开出的证明可用于？
- 亲历可开出病历/证明的基本状况和时间

**Comment by NKNaN** [comment]
我也不在四川住ort，只能等下次有机会的话再去看看，不过上次去找李医生她说这个病历还是可以在隔壁人民医院开hrt的

**Comment by ArielHeleneto** [comment]
本垃圾满18，无家长。在做了mmpi，mf95分的情况下，获得口头建议“开始hrt”。李医生似乎因为各类原因不在病历上写这些，但是依然会写诸如”mmpi提示女性化指数高”等内容，但尚未确认能不能hrt。

李医生称”22岁后可以开证”

2022-07-18就诊

**Comment by Aleksanaa** [comment]
> 本垃圾满18，无家长。在做了mmpi，mf95分的情况下，获得口头建议“开始hrt”。李医生似乎因为各类原因不在病历上写这些，但是依然会写诸如”mmpi提示女性化指数高”等内容，但尚未确认能不能hrt。
> 
> 李医生称”22岁后可以开证”
> 
> 稍后会放出电子版病历
> 
> 2022-07-18就诊

啊，这
6月27日时去刚好不行，今天去看了任正伽结果李慧刚好可以，有点生气（

**Comment by tonori** [comment]
2022年7月25日，拒绝接诊

**Comment by ArielHeleneto** [comment]
2022-07-26 李慧已经明确拒绝接诊相关病人且拒绝开证，但是会和家长沟通。

**Comment by Aleksanaa** [comment]
> 2022-07-26 李慧已经明确拒绝接诊相关病人且拒绝开证，但是会和家长沟通。

李慧的可行状况真的是按周刷新的

**Comment by ArielHeleneto** [comment]
> > 2022-07-26 李慧已经明确拒绝接诊相关病人且拒绝开证，但是会和家长沟通。
> 
> 李慧的可行状况真的是按周刷新的

我觉得是按“某部门”刷新的

**Comment by tonori** [comment]
我去的时候甚至感觉不到所谓的“耐心 / 温柔”，从进诊室到出诊室用时应该没超过 5 分钟。我能理解李慧医生，但我不会再去她那了
