### ISSUE TITLE
深圳市康宁医院张倩 观察期

### ISSUE THREAD

**Issue by Lumine1919** [mtf-wiki/MtF-Wiki#509]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/pearl/shenzhen-kangning/

### 内容

已满 18，未 RLE，有两年观察期。

![深圳康宁张倩观察期](https://user-images.githubusercontent.com/100746107/175356431-1e4b897a-b029-4fd4-b034-1491bb491747.jpg)

**Comment by ArtsEpiphany** [comment]
感谢反馈！请问观察期的具体条件是什么？是父母不同意就需要两年观察期吗，还是有其他因素的影响呢？

**Comment by Lumine1919** [comment]
应该就是父母不同意，同行的另外一位也是两年观察期。

**Comment by ArtsEpiphany** [comment]
内容已添加，如果未来情况发生变化欢迎反馈。
