### ISSUE TITLE
关于目录的命名和结构的问题

### ISSUE THREAD

**Issue by Fe3O4-Git** [mtf-wiki/MtF-wiki#528]
1. 如果遇到一个医院仅有一个医生的情况，目录命名应该使用医生名字还是医院名称，目前咱发现二者都有，如 psyco/midsouth/cheng-ming(长沙市第二人民医院-程明) 和 hrt/xiangya3(湘雅三院-龙智)
2. 如果遇到一个医院有多个医生的情况，应该把ta们移入一个以医院命名的目录吗，咱目前发现 psyco/midsouth/zhang-xiaocui(湘雅二院-张小崔) 和 psyco/midsouth/he-ying(湘雅二院-贺莹)未合并，但 psyco/bhlgh 则是一个合并过的目录
3. 如上 psyco 目录下有地区分类，但 hrt 目录下没有
4. 目录命名有些缩写使用英语，有些使用拼音，还有些使用拼音首字母，是否应该统一

**Comment by ArtsEpiphany** [comment]
感谢你对这个问题的关注。其实你应该也能看出来，最早的时候wiki在命名上并没有严格的规范，因此命名与结构不一致的问题大量存在。我们也在努力去将它们规范化，至于具体的方案，我想可能据要进一步的讨论。

我可以大概解释几件事情，第一是为什么北京回龙观医院要合并为一个页面。这是因为该院开具诊断证明的要求是每三个月就诊一次，一年后可以开具诊断证明，而每次就诊是哪个医生并不重要。你既可以每次都找同一个医生，也可以每次换一个医生。因此将他们合并到一起就很有必要，因为这个就诊过程是以医院为基本单位进行的。我们可以在医院的页面讲解这个医院的挂号方法、就诊流程等等，而无需在每个医生处分别记录一次。

第二是为什么有的医院没有合并为一个页面。首先是，这些医生有的独立性强，每个医生对于开证有自己的标准，这个时候他们除了在同一家医院之外没有太多的共通之处，所以不必合并为同一个页面。还有一点就是没有合并的情况往往是只有两名医生，这个时候合并不能让页面整洁太多，反而多了一级跳转，这也会降低效率。（其实现在wiki的效率就已经比较低了，文档->精神科->地区->医院->医生，我自己每次想查个页面都要点上半天。）

第三是目录命名的问题。这个其实一直都很随缘，人们想怎么起名就怎么起名。我个人的建议是，以讲述医生情况为主的页面（比如医生和不和蔼，劝不劝家长等）应当以医生命名，而以讲述医院情况为主的页面（比如挂号、检查、缴费流程等）应当以医院命名。

另外，psyco目录下有分类是因为psyco下的医生数量比较多，而hrt下的医生（至少在早期）比较少，当时没有这样分类的必要。随着医生的不断增多，我们也该考虑进行类似的分类了。

**Comment by septs** [comment]
@Fe3O4-Git 目前结构方面已经做了一些调整

1. 精神科依照行政区划划分
   具体参见 https://github.com/mtf-wiki/MtF-wiki/commit/47c50e20a8da5225f4bf2ea41cdbb8eca140e4ab

2. 移除未存在实质内容的语言支持
   具体参见 https://github.com/mtf-wiki/MtF-wiki/commit/0581baa6782952d5020b277a192273c4fc2d3158

3. 不存在统一风格问题，不同的命名规则有各自的目的

   1. 例如对于仅具有中文名称的东西（事物），此时使用拼音字母的方式处理较为简单

   2. 虽然 医院的态度 也很重要，但是如果 医师的行医风格 有较大的差别
      合并的结果是带来全文逻辑自洽性的问题

   3. 行政区划划分，远期来看是有可能被取消的
      从目视查找的角度来说，您对您熟悉的城市名称相较于 行政区划/经济区划 更具有 熟悉性
