### ISSUE TITLE
雌二醇凝胶页面中的疑惑？

### ISSUE THREAD

**Issue by tuboshufps** [mtf-wiki/MtF-Wiki#543]
https://mtf.wiki/zh-cn/docs/medicine/estrogen/gel/
pre above: "涂抹面积不应过大"

https://mtf.wiki/images/medicine/gel/estradiol-gel.jpg
pre above:
"【用法用量】：本品经皮给药:将药物涂抹于较大面积的皮肤上"
"【药代动力学】：药物在表皮角质层有短暂的贮存。药物自给药部位经皮内毛细血管缓慢扩散进入全身血液循环"

https://www.bilibili.com/video/BV1eq4y1U71L
pre above:
"01:51：尽可能让爱斯妥凝胶变薄，均匀分布在皮肤上“

后两个链接虽然没有直接说明涂抹面积的问题，但通过逻辑推断，是希望涂抹面积较大比较好，与Wiki界面冲突。
望editor考量双方可信度或依照专业人士建议后进行修改或保留
thx

**Comment by saeziae** [comment]
根据研究，吸收和涂抹面积的关系是一条有峰值的曲线，意味着不能够无限制扩大涂抹面积，“涂抹面积不应**过大**”也是基于这个现象，大概就是说不能大腿、手臂、腹部都涂一点。将修改本页面以澄清歧义。

**Comment by saeziae** [comment]
59aa86e82d02cf3cae0dce5b0d80bf45b019ca3d
