### ISSUE TITLE
【条目补充】深圳｜王晓京

### ISSUE THREAD

**Issue by meownotmiao** [mtf-wiki/MtF-Wiki#551]
### 医院名称

北京大学深圳医院

### 医生姓名

王晓京

### 标签

LGBT+ 友善, 初诊获得证明/假条

### 交通：
①开车需要提前预约车位，车位极少，入场时间很久，不推荐！
②深圳地铁2/9号线景田站D出口，出去后直行约500米

### 挂号：
1. 微信公众号「北京大学深圳医院」→特诊心理科
2. 健康160→「北京大学深圳医院」→特诊心理科

*好大夫在线**无法**挂到他的号
*放号随机（放哪天的号随机）每天下午15:00可蹲点看有没有号；号源较少，每天**首诊**只看2~4个号
*预约挂号不收取费用

### 基本费用：

挂号费25元（需取号时支付）+特诊费500元（就诊后再支付），两项都支持医保

### 取号：

每层都有自助取号机，可以凭身份证、医保卡、电子医保卡、取号密码等方式取号，外地人可不需要就诊卡！
***不需要买病历**，现在深圳医院病历除了特殊需要以外已经全部电子化了！
***取号后即加入叫号流程，请到6楼后再取号！**

### 出诊地点：

门诊6楼出电梯后右转/出楼梯后左转，然后再右转走到尽头，31号特诊诊室，比较难找，建议提前到达！如果已经有人在就诊，门是无法从外面打开的，请敲门后耐心等待！

### 问诊：

直接向他表达你的想法，就跟心理咨询一样聊天，王医生很好讲话。主要会聊一些你小时候的经历，你的心路历程，为什么想要改变性别，你的性取向（以前和现在的性兴奋对象），你的学习怎么样等。
*王医生在一开始聊天时，可能会劝退你，会跟你说这怎么怎么不好，（改变性别这条路）怎么怎么难走，名字太男性化也会被吐槽，**如果立场不坚定，就直接劝退，不会开证！**
***不要一上来就说自己有性别焦虑，要具体到详细的一点！**
最后通过谈话，如果医生觉得你已经坚定地要走这条路，便会开具证明，并且祝福你！
*医生对跨的一些知识可能有点落后了（毕竟也是很久以前留的学），可以当面指出来并且纠正
*医生不吃人，就放心说，不要紧张（如果有特殊癖好的就不必说出来了），家长在旁边的话说一些事请慎重！
***未成年可一次性开证，但未成年家暴党/深柜党能否开证，未知！**

### 量表/开药：

①如果你有其他精神疾病，如抑郁、睡眠障碍等问题，会一并开具药物！
②医生可能开具MMPI-2等量表！笔者就诊时因为时间已晚，就没有开具，但笔者先前在网上做过，就直接给王医生看了（Mf分数）
*建议可以自己在网上提前做一下MMPI-2（价格30元左右），看一下自己的Mf分。
*MMPI-2【注意是二代MMPI】：微信公众号「艾瓦科技」→测评/工具→MMPI-2完整版

### 不推荐情况：

①没有很强烈的改变性别的意愿，可能不予一次开证（笔者后面貌似有一位复诊的MtF，估计是没能一次开证）
②有其他较严重的精神障碍
③不够pass【言行举止外貌等不够女性化，但不需要伪声】（建议女装前往，但不要太辣眼睛那种就行）
④家暴党，家长去捣乱

### 后续：
开证后，拿着证明到一楼入口旁边的诊断证明书盖章处，直接给护士小姐姐盖章即可。
***注意医院下班时间大概在17:00左右！**

### 证明样式

![1](https://user-images.githubusercontent.com/31438099/179147882-214710a6-3f3c-4042-bf4f-9d36c779885f.jpg)

### 以 CC-BY-SA 4.0 协议分发

- [x] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by meownotmiao** [comment]
MtF.wiki URL：https://mtf.wiki/zh-cn/docs/psyco/pearl/wang-xiaojing/

**Comment by septs** [comment]
Redirect to #623
