### ISSUE TITLE
对西安电子科技大学的军训情况有误

### ISSUE THREAD

**Issue by RebelRedGuards** [mtf-wiki/MtF-Wiki#557]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/campus/china/xdu/

### 内容

本人为了西安电子科技大学2020级本科生，刚刚参加完军训，发现网站上所写完全背离事实。
![Screenshot_2022-07-21-16-21-58-37_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/92835056/180170679-14a82d60-8d04-4e6d-9e6e-6c47454fc2a6.jpg)

但实际上，西电军训毫无头发要求。长头发生理男生（多为顺性别男性)均扎辫子参加军训。
此外，根据我对2019级学长的调查，他们的军训亦没有头发长度要求。
附本人军训时照片为证
![IMG_20220627_233907](https://user-images.githubusercontent.com/92835056/180170905-1bb4e570-2fb9-4edb-b73f-0e2ed44ae948.jpg)

**Comment by septs** [comment]
CC @CamberLoid

**Comment by CamberLoid** [comment]
> ### MtF.wiki URL
> 
> https://mtf.wiki/zh-cn/docs/campus/china/xdu/
> 
> ### 内容
> 
> 本人为了西安电子科技大学2020级本科生，刚刚参加完军训，发现网站上所写完全背离事实。
> ![Screenshot_2022-07-21-16-21-58-37_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/92835056/180170679-14a82d60-8d04-4e6d-9e6e-6c47454fc2a6.jpg)
> 
> 但实际上，西电军训毫无头发要求。长头发生理男生（多为顺性别男性)均扎辫子参加军训。
> 此外，根据我对2019级学长的调查，他们的军训亦没有头发长度要求。
> 附本人军训时照片为证
> ![IMG_20220627_233907](https://user-images.githubusercontent.com/92835056/180170905-1bb4e570-2fb9-4edb-b73f-0e2ed44ae948.jpg)
> 

hi~

感谢指出~这里是按照咱当时2018级的印象写的，因此可能存在一定程度的偏差。

**Comment by CamberLoid** [comment]
这里还请麻烦您提一个PR来修正过时/不正确的表述~感谢~
