### ISSUE TITLE
中北大学本部（需政治审查，谨慎填报）

### ISSUE THREAD

**Issue by Wu-XR** [mtf-wiki/MtF-Wiki#561]
### 学校名称

中北大学

### 地址位置

山西省太原市

### 宿舍独立卫浴

无

### 教学区第三卫生间

无

### 军训减免

军工院校需深柜者进入，医学材料情况不详

### 军训管不管头发

管

### 体育减免

不详

### 医保的可用情况

总之易性症不可

### 校医院可用度

不可

### 现状梗概

从一个朋友那里了解到的，理论上深柜是可以进入的。
此高校以军事工业方面为重点培养项目，属于国家六所保密大学之一，名不见经传。
此高校重点学科挂科率奇高，但是不挂科就可以拿到红头文件，就算挂科最后很多也能被北方工业公司接收，不挂科毕业甚至有可能参与到一些需严格政审的工作。至于研究生阶段可以考虑到北京理工大学。
还是作为一个铁饭碗跳板，如果考虑深柜很长时间的朋友可以尝试一下，但是易性症出柜会不会被开除还有待更多人探讨（不包括关系户）。
就读分数条件较为轻松（对于重点高校的摸鱼者来说），按照文理地区分数来说550以上就可以报考到一些好的专业，武器设计原理需要580以上。主要还是保饭碗用。
校舍为上世纪就存在，很古老的，条件相比某些高校较差。但是教授学科内容是非常好的，优秀者有可能以后可以到各地的武器设计研究所进行工作，那个时候出柜也不迟。
（据称南理曾经有过军工药娘，而且饭碗没丢）

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Wu-XR** [comment]
顺便认识几个军工药娘，这里不方便透露了

**Comment by Wu-XR** [comment]
中北校舍从上个世纪80年代一直到现在都是这样子，改了改，天天修，除了瓜好吃点其他也就将就点吧。。。

**Comment by septs** [comment]
由于需要长期深柜，因此我认为普适性不足

**Comment by Wu-XR** [comment]
> 

这方面如同TNO高宗武，潜伏味道确实浓厚，不过个人觉得如果称得下来可以给国内屁民媒体造桩大事

**Comment by Wu-XR** [comment]
> 由于需要长期深柜，因此我认为普适性不足

顺便做个预防性介绍，我觉得可以，万一真有人不小心报到了就不好了
