### ISSUE TITLE
校园指南投稿-哈尔滨工业大学（深圳） - HITSZ

### ISSUE THREAD

**Issue by mMHog** [mtf-wiki/MtF-Wiki#562]
### 学校名称

哈尔滨工业大学（深圳）

### 地址位置

广东省深圳市南山区深圳大学城

### 宿舍独立卫浴

有

### 教学区第三卫生间

部分有

### 军训减免

不了解

### 军训管不管头发

不了解

### 体育减免

不了解

### 医保的可用情况

不了解

### 校医院可用度

不了解

### 现状梗概

本人通过邮箱投稿未获得反馈，请以此最新版本为准，感谢！

[HITSZ.md](https://github.com/mtf-wiki/MtF-Wiki/files/9167592/HITSZ.md)

### 以 CC-BY-SA 4.0 协议分发

- [x] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Inondup** [comment]
[HITSZ.md](https://github.com/mtf-wiki/MtF-Wiki/files/9172891/HITSZ.md)
最新修改版

**Comment by h0gan1ee** [comment]
补充一些信息：
- 第三卫生间：信息楼有（其实是无障碍卫生间），大多数教学楼没有，但是在男/女卫生间里面有无障碍隔间。
- 医保：少儿医保。经社康转诊可去南方科技大学医院（三级，非三甲）就诊。
- 校医院：无。清华园区和平山村内有社康，但是急诊一般都只能去深圳大学总医院（三甲）和南科大医院。

**Comment by septs** [comment]
考虑到已存在三份版本，且各自作出了修改意见
因此建议 @mMHog @h0gan1ee @Inondup 三方共同编纂一份自洽的版本进行提交
