### ISSUE TITLE
希望能开设恐跨医生/医院板块

### ISSUE THREAD

**Issue by nexplorer-3e** [mtf-wiki/MtF-Wiki#573]
（避免重复踩坑什么的）

**Comment by truthcracy** [comment]
感觉wiki上挂这个可能不是很合适，但是确实觉得社群十分需要有一个。

**Comment by septs** [comment]
建议去 https://chat.transland.lgbt 或 https://limelight.moe 进行讨论

**Comment by nexplorer-3e** [comment]
plz attach some standards/roadmaps if possible thanks

发件人: ***@***.***>
发送时间: ‎2022‎年‎7‎月‎28‎日, ‎星期四 ‎19‎:‎06
收件人: ***@***.***>
抄送: eval ***@***.***>, ***@***.***>


Closed #573<https://github.com/mtf-wiki/MtF-Wiki/issues/573> as not planned.

**Comment by BeiyanYunyi** [comment]
我觉得反向确认列表可能会被拿去逆练，后果比友跨医生列表上的医生被骚扰还糟糕一些。因为友跨医生列表的医生被骚扰、施压，承压的是医生，跨性别社群属于间接受压，并且就功利主义原则来说，一般而言仍然是为更多的人争取到了更多的幸福，利益受损的一般是小部分人。而反向确认列表就糟糕了，反跨家长可能直接带孩子就去，这就是直接受压。
