### ISSUE TITLE
重庆大学更正

### ISSUE THREAD

**Issue by Wu-XR** [mtf-wiki/MtF-Wiki#585]
重庆大学的一些专业诸如安全工程存在保密要求，请各位填报时对专业保密性进行查明查实在明确填报。其内部流通秘密包含了各种等级，因此有保密协议。一旦外露，后果极大可能自负。
达成保密协定之后出柜在理论上倒是不会开除，但是会很难堪

**Comment by septs** [comment]
本编辑认为无法采信，建议邀请在校生进行报告
