### ISSUE TITLE
移动版首页左上角的两个按钮是否会造成困扰

### ISSUE THREAD

**Issue by Fe3O4-Git** [mtf-wiki/MtF-Wiki#587]
如图1所示，用移动设备访问本站首页会出现以下两个按钮
![图1](https://user-images.githubusercontent.com/61769640/182029566-2de4456f-58ad-4a4a-9a36-7664489933ee.jpg)
点击后分别会出现图2和图3的菜单
![图2](https://user-images.githubusercontent.com/61769640/182029636-63e85b0a-e7a6-4714-a7e6-d729fbff0b93.jpg)
![图3](https://user-images.githubusercontent.com/61769640/182029655-c6534fcf-7c90-4087-b257-ec61af232824.jpg)
估计大多数人访问网站后会先尝试点击按钮1，但点击按钮1得到的菜单(即图2所示的菜单)是一个空菜单，所以这可能会造成一些困扰
可能的解决方法:
- 在首页隐藏按钮1
- 把图3所示菜单内的项目同步到图2所示的菜单
- etc

**Comment by septs** [comment]
目前工作组内有设计师正在设计新版站点，敬请期待。
