### ISSUE TITLE
繁体页面显示的螺内酯用量与简体不一致

### ISSUE THREAD

**Issue by n78** [mtf-wiki/MtF-wiki#607]
### MtF.wiki URL

https://mtf.wiki/zh-hant/docs/medicine/antiandrogen/spironolactone/

### 内容

螺内酯片用量：相同页面中，简体中文版显示的为「40-200mg/天，分多次服用」；繁体版却是「100-200mg/天，一次用药，不分多次」。疑似繁体页面过时，未随简体页面一同更新。
另：建议使用简繁转换工具如 [OpenCC](https://github.com/BYVoid/OpenCC) 等，实现类似中文 Wikipedia 的效果，而不是为简体和繁体各自单独编写一个页面，容易导致页面更新时内容不同步。

**Comment by saeziae** [comment]
已于 1f8b8e7385c8a969f933b348bccd651b1b23b764 修正。
MtF Wiki 的简体中文与繁体中文版面并非简单的同一内容的不同文字的关系，而与内容本地化有更多关联，在许多页面上存在内容的差异，这些页面无法通过简单的机器转换产生。一些内容完全一致的页面确实由 OpenCC 转换而来，我们正在思考这些关联页面的同步方法。
