### ISSUE TITLE
北京大学第三医院内分泌科的刘烨医生

### ISSUE THREAD

**Issue by ArielHeleneto** [mtf-wiki/MtF-wiki#618]
### MtF.wiki URL

https://www.haodf.com/doctor/2168666201/xinxi-menzhen.html

### 内容

根据刘烨医生的 [好大夫主页](https://www.haodf.com/doctor/2168666201/xinxi-menzhen.html) 的相关内容以及 2022-08-14 挂号系统的查询，有充足的证据表明刘烨医生暂时不能进行相关治疗。

> 个人停诊通知 更新于2022/08/01
> 停诊时间：2022/07/31至2023/02/01；停诊备注：外派工作

尚不能确认该原因真实性。

**Comment by septs** [comment]
Duplicate of #619
