### ISSUE TITLE
北医三院 ”内分泌门诊 - 易性症激素治疗门诊” 无法挂号

### ISSUE THREAD

**Issue by ArielHeleneto** [mtf-wiki/MtF-wiki#619]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/hrt/puth/

### 内容

由于未知原因，114平台上 [北京大学第三医院内分泌门诊-易性症激素治疗门诊](https://www.114yygh.com/hospital/142/df36d93f187b96af86dc27ae84a05bb7/200075482/source) 完全无号，公众号也无法查到该科室。

**Comment by septs** [comment]
刘烨 与该 issue 需要合并讨论

**Comment by BikerDuality** [comment]
已提交修改
