### ISSUE TITLE
浙大二院 已丧失开证资格

### ISSUE THREAD

**Issue by tuboshufps** [mtf-wiki/MtF-wiki#641]
根据最新的面诊结果 浙二已经无法开出诊断证明，请求删除 

https://mtf.wiki/zh-cn/docs/psyco/zhejiang/yang-linglin/
https://mtf.wiki/zh-cn/docs/psyco/zhejiang/sahzu/

并添加至已过时列表

来源 https://twitter.com/yinchao_qaq/status/1567454283205070850
以及一些同城朋友的反馈

**Comment by septs** [comment]
等待多来源报告

**Comment by septs** [comment]
https://twitter.com/Windy_Skyline/status/1567537097195536386

https://twitter.com/Windy_Skyline/status/1567533843384524800

**Comment by LotteWS** [comment]
关于浙江大学医学院第二附属医院已不具备开局诊断证明的说法存疑。

根据我个人的就诊经历，判断有医生没有告知就诊人真相的可能性。

杨琳玲医生在拒绝开出诊断证明后，经我询问告知：浙二已无法开出诊断证明。
但我在问诊其他医生后仍然轻易开出了诊断证明。
![821C2DD3-36DB-49E6-A6E8-C5FD43372D2F](https://user-images.githubusercontent.com/79241248/189942331-3c43086b-2130-4df5-b270-8304f7b07355.jpeg)

根据近期陪同多位朋友就诊的经历，我认为浙二的开证、配药流程都没有一个统一的标准，内分泌科还有极度不友好的医生告知浙二连拿着自家医院的诊断证明也不能开药（本人亲自在内分泌科其他医生出诊时开药已证明是医生说谎，投诉无效）。

所以我个人认为，浙大二院是否能开局诊断证明，甚至只是开局病例，决定权都在医生个人手上。

以下是我就诊经历：
初诊，叫号进入1410诊室就诊，出诊医生为杨琳玲。
进门后，医生简单询问是来看什么问题的，之后开始对话。
（内容中“·、-”所代表的人物与身份无关，只与每段对话中两人开口的先后顺序有关）

·“这种想法有多久了？”
-“从小学毕业就有了。”
·“平时都是这个打扮吗？还是只是今天来就诊是这样穿的？”
-“平时就是这样穿的。”
·“从什么时候开始这样穿着的呢？”
-“上了大学离开家之后就自己想穿什么就穿什么了。”
·“嗯。”
·“精神状况方面有其他的问题吗？”
-“之前有过，我从家里搬出去之后就好多了。”
·“你喜欢男生还是女生呢？”
-“不管性别是什么样的，我都有可能会喜欢，男生、女生，还有性别认同是其它的”
·“哦，刚才站在门口的是你男朋友吗？”
-“是的。”
·“那他喜欢什么性别的人呢，男生还是女生？”
-“他应该是泛性恋。”
·“泛性恋？”
-“就是也是不管什么性别都有可能喜欢。”
·“哦我还是第一次听说呢。”
·“家里知道这个情况吗？”
-“我不打算告知家人，我之前精神状况很差，自从大二自己出去住之后就好多了。”
·“那你之后总有一天要让家里知道的呀。”
我不说话。
·“我给你开几个测试，去旁边做一下，之后去分诊台扫码复诊。”
-“好的，谢谢。”

做完几个测试，结果均没有什么异常，只有睡眠问题以及MMPI mf分数较高，拿着结果复诊。

·“进那个小程序，把结果给我看一下吧。”

我拿出手机，去翻刚才测试的结果，医生的视线一直停留在我涂的指甲油上。
医生翻阅了几个测试的结果。

·“嗯，你这种情况，确实是属于易性症，我还是建议你告知一下家长的，然后如果有其他精神方面的问题的话也是不建议进行手术的。”
-“嗯好的。”

医生开始打字，强调状态持续时间、着装女性化时间以及mf分高，之后打印出了病历单，我拿到之后道谢离开，突然想起来诊断证明这件事，于是又敲门进去询问。

·"你好,刚才忘记问了,能帮我开一下诊断证明吗?" 
-"开诊断证明是要做什么用的呢?" 
·"我怕有的时候会遇到误会,有诊断证明可能会好一点。" 
-"那你有病例不就行了吗?" 
·"那现在是不能开这个证明了吗?" 
-"我们这边都不会再开这个诊断证明了" 

此时我已经认为，浙江大学医学院附属第二医院已经不具备开证条件了。
但是我第二天还想碰碰运气，于是又挂了号。

此次出诊医生：金嘉郦

叫号之后进入诊室。

·"你好,我之前来问诊过,可以看一下之前的病例,能帮我开一份诊断证明吗?" 
-"好的。" 

医生打字，在原有病例上添加：“要求开具证明”
之后打印出了新的病例与诊断证明

-"你还需要别的什么吗?" 
·"不需要了,谢谢"
-“诊断证明去一楼的门诊综合服务中心盖章后有效。”
·“好的，再见。”

于是第二次就诊就这样没有任何阻力我就拿到了诊断证明。所以我认为浙二并不是不能开局诊断证明了，而是有的医生因为自己有某些考虑，为了打消患者来此就诊的念头去告诉患者浙二无法开局诊断证明甚至是病例。

**Comment by septs** [comment]
https://github.com/mtf-wiki/MtF-wiki/commit/bcaeb2ca737d27de86b3972d395785452bd334ba

**Comment by Cryolitia** [comment]
![Screenshot_20230716-130433.png](https://github.com/project-trans/MtF-wiki/assets/23723294/71f35d5a-74d7-42cd-afb1-3f1164fa7a9f)

https://twitter.com/yinchao_qaq/status/1567454283205070850
