### ISSUE TITLE
未成年在回龙观医院取得实体京医通卡

### ISSUE THREAD

**Issue by USS-LongIsland** [mtf-wiki/MtF-wiki#660]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/beijing/bhlgh/di-xiaolan/#%e6%b3%a8%e6%84%8f%e4%ba%8b%e9%a1%b9

### 内容

2021年初就诊时16周岁，在回龙观医院取得京医通实体卡时未被要求提供家长身份证。
16周岁以下有待考证(?

**Comment by septs** [comment]
并入 #623 进行讨论
