### ISSUE TITLE
WIH 收款账户 与 WIH 的关系说明页面已 404 无法访问

### ISSUE THREAD

**Issue by ljtjerry** [mtf-wiki/MtF-wiki#677]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/srs/thailand/chettawut/

### 内容

THANADOL & KOJCHABOON CO., LTD.（收款账户）与 WIH International Hospital 的关系说明页面已404无法访问

“此页面”这个超链接，地址是https://wihhospital.com/privacy-policy
wih其它页面可以正常访问
<img width="1699" alt="image" src="https://user-images.githubusercontent.com/13274938/201589733-983a161d-91e6-4fa1-8d08-6837fc7a4e39.png">

**Comment by septs** [comment]
Internet Archive 可追溯到在 2022 年 1 月 27 日是可以访问的

https://web.archive.org/web/20220127113829/https://wihhospital.com/privacy-policy

**Comment by dev-soragoto** [comment]
https://github.com/mtf-wiki/MtF-wiki/commit/a5b686f397340f5a380ab3610f1cb4b7b38fc6b4

fixed
