### ISSUE TITLE
Translation mistake (JA)

### ISSUE THREAD

**Issue by kotonefami** [mtf-wiki/MtF-wiki#684]
At Japanese top page:
```
MtF.wiki へようこそ。 吾輩は、トランスジェンダー女性に関する情報を整理して要約し、より良い支援を提供するよう努めています〜
```

The mistake I found is that it is "私たち" and not "吾輩", was this intended?
I think "吾輩" is used in fiction and is not appropriate for a page explaining something.

**Comment by saeziae** [comment]
That was a salute to Natsume Sōseki’s _I Am a Cat_ , as cat is imagery used by many trans and enby.
You can still comment if you think it inappropriate using this word here.

**Comment by kotonefami** [comment]
I thought it might be a translation error, but if that is what was intended, I don't see the problem.
Sorry to bother you.
