### ISSUE TITLE
rename 'content/zh-cn' to 'content/zh-hans'

### ISSUE THREAD

**Issue by sayo-melu** [mtf-wiki/MtF-Wiki#69]
also 'zh-t' to 'zh-hant'

**Comment by LaoshuBaby** [comment]
附议

**Comment by saeziae** [comment]
会影响既有的引用和分享的链接

**Comment by Misaka13514** [comment]
不建议修改
- 不作重定向
  - > 会影响既有的引用和分享的链接
- 301重定向
  - GitHub Pages 无法301重定向
  - 站点也没设置其他 CDN
- html tag / javascript
  - Hugo i18n 感觉有问题（
    - bb8fca05f603b2ff51c0a167e02074fc065ffaff
      生成后部分子文件夹在`zh-cn`下 暂不清楚如何修改 ~~CI的时候sh hack下~~

**Comment by undefined-moe** [comment]
可以考虑做个alias之类（？

**Comment by septs** [comment]
BCP 47 标准的建议确实应当更改为 `zh-hans`，但是考虑到 SEO 的影响及根据 Google Search Central 提供的建议

https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls
https://developers.google.com/search/docs/advanced/crawling/managing-multi-regional-sites

我认为需要等待我们开发出新的 theme 同时，同步进行该项变更程序

**Comment by septs** [comment]
考虑到 mtf.wiki 简体中文内容的均基于中国大陆的客观实事撰写
因此切换到 `zh-hans` 在目前内容不具有普适性的前提下
我觉得不太合适

**Comment by saeziae** [comment]
projecting to use `zh-hant` and keep `zh-cn`

**Comment by Cryolitia** [comment]
尊敬的贡献者您好，我们在近期启动了《MtF.wiki 站点国际化设计提案》的起草与表决工作，您可以前往 https://github.com/project-trans/summit/pull/1 参与讨论，感谢您对 MtF.wiki 的关注与支持！
