### ISSUE TITLE
辽宁-大连

### ISSUE THREAD

**Issue by ChisakaKanako** [mtf-wiki/MtF-wiki#693]
### 医院名称

大连市第七人民医院

### 医生姓名

张亮

### 标签

初诊获得证明/假条, 需要家长介入

### 注意事项

会询问是否服用过激素、近期是否有自伤行为、自我认同程度、未来规划以及家长是否知情并且支持等等……
如之前有过该院诊断记录，会询问治疗情况，例如抑郁焦虑等是否缓解、是否有持续用药等……明确心理性别认同后也会建议进行为期一年的心理治疗。

### 证明样式

![大连市第七人民医院门诊诊断书](https://user-images.githubusercontent.com/103566952/205955968-2f394dbf-905f-43f3-ac5d-71ff9501ddae.jpeg)

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Rinfair-CSP-A016** [comment]
Closed due to commit 31a284d
