### ISSUE TITLE
Kamol价格错误

### ISSUE THREAD

**Issue by sourceoflife123** [mtf-wiki/MtF-wiki#699]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/srs/thailand/kamol/

### 内容

结肠（腹腔镜）价格为599000泰铢
其他的我还在问

**Comment by Harriet-Muggle** [comment]
Verifying. 

Rgds,
Harriet Li

**Comment by Harriet-Muggle** [comment]
腹膜 {{< currency 625250 THB >}} dtd 2022/12/07

**Comment by Harriet-Muggle** [comment]
腹膜 {{< currency 725250 THB >}} dtd 2022/12/07

**Comment by Neko-aLIEz** [comment]
Force update SRS pricing from Kamol official pricing list.

https://github.com/mtf-wiki/MtF-wiki/commit/f260829d93f76a999ec71507cd01b5102b8f9d02

**Comment by Neko-aLIEz** [comment]
> 

没问题，我这边来进行更正

**Comment by Neko-aLIEz** [comment]
9f5c11ecbd851d17bc5369aa53e54c88d4ecbfb1

**Comment by Neko-aLIEz** [comment]
Because pricing updated with official. If anyone has issue please reopen this issue.
