### ISSUE TITLE
目前回龙观病历复印似乎并不收取费用

### ISSUE THREAD

**Issue by Chat6942** [mtf-wiki/MtF-wiki#701]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/beijing/bhlgh/#copy

### 内容

似乎目前回龙观进行病历复印并不收取费用。

**Comment by piggynl** [comment]
根据本人 2022 年 12 月 22 日的就诊经历可证实。

**Comment by ArielHeleneto** [comment]
根据本人 2022 年 12 月 28 日的就诊经历可证实。但是会询问病例用途（你可以装死）

**Comment by creamlike1024** [comment]
根据本人 2023 年 2 月 3 日的就诊经历可证实。

**Comment by septs** [comment]
Redirect to #623
