### ISSUE TITLE
关于刘宏医生相关信息的补充

### ISSUE THREAD

**Issue by Arlia-Etoile** [mtf-wiki/MtF-wiki#724]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/liaoning/liu-hong/

### 内容

挂号方式：

可以通过“大连市第七人民医院“小程序（微信、支付宝均可）提前在网上进行挂号，建议提前至少1-2天挂号，虽然刘宏医生的号源比较充足，但线下当日挂号很可能挂不上，在此推荐使用线上小程序挂号，号源更充足。

以下为挂号单图片，挂号费16元。

<details>
<summary>挂号单</summary>

![挂号单](https://user-images.githubusercontent.com/70079806/214482298-60092347-5452-4140-94f0-5f33836d0eb7.jpeg)

</details>

问诊细节：

如果是首诊，请先在大连市第七人民医院一楼总服务台填写首诊信息单。

注意⚠️：填写首诊信息单前，需要交60元首诊费，可通过微信/支付宝小程序缴费。

<details>
<summary>首诊费</summary>

![首诊费](https://user-images.githubusercontent.com/70079806/214482303-a13a395e-9a8d-4d4c-9e11-5bcaa346625d.jpeg)

</details>

检查项目：

1. 问卷类项目

<details>
<summary>MMPI</summary>

大连七院的 MMPI 总题数仅176题，大约15分钟内可以做完，平均完成时间在10分钟左右，而且没有固有印象类题目，可放心作答。

以下为MMPI问卷结果的样式

![问卷结果样式-明尼苏达（176题）](https://user-images.githubusercontent.com/70079806/214482266-86ec32d1-3ce1-4c43-8c47-cb6e4363a853.jpeg)

</details>
<details>
<summary>症状自评量表（名称应改为“90项症状测验量表”）</summary>

以下为90项症状测验量表问卷结果的样式

![问卷结果样式 - 90 项症状测验](https://user-images.githubusercontent.com/70079806/214482261-23d96aa2-f2f7-4adb-bfee-fa82bdad2c38.jpeg)

</details>

<details>
<summary>艾克森个性测验</summary>

以下为艾克森个性测验问卷结果的样式

![问卷结果样式-艾克森个性测验](https://user-images.githubusercontent.com/70079806/214482258-84f5bdcd-93fb-45db-b44c-3bca0ae7e068.jpeg)

</details>

2. 脑科项目

<details>
<summary>脑CT</summary>

脑CT检查与取片位于大连七院***3号楼***一楼

以下为脑CT检查结果样式示意图

![检查结果样式-脑CT](https://user-images.githubusercontent.com/70079806/214482273-546df829-dafa-4c7a-b0d4-702b9d263eef.jpeg)

![检查结果样式-脑CT-X光片](https://user-images.githubusercontent.com/70079806/214482285-36eb95ef-b489-4817-ba1a-49f4fc5d7b7a.jpeg)

注意⚠️：装“脑CT-X光片”的袋子左上角的**条形码**，是取“脑CT检查结果”与“脑CT-X光片“用的，给你做脑CT的医生会在做完脑CT后将条码打印出来贴在装“脑CT-X光片“塑料袋上，**请务必好好保管塑料袋及其上的条形码，丢失后将无法取得“脑CT-X光片“及检查结果**。

</details>

<details>
<summary>脑电图</summary>

注意⚠️：建议携带酒精湿巾与梳子，大连七院所使用的导电膏极其粘头发，需反复清洗才能洗掉

以下为脑电图检查结果样式示意图

![检查结果样式-脑电图](https://user-images.githubusercontent.com/70079806/214482269-e9ecde43-5eaa-4725-a8f8-ca949901e7c2.jpeg)

</details>

4. 抽血检验项目

<details>
<summary>性激素五项</summary>

注意⚠️：**就诊日当天**就会进行性激素五项检验，请**不要吃早餐**。
注意⚠️：性激素五项**不包含**泌乳素检查。
注意⚠️：本检查的结果会发送到微信/支付宝小程序上，可以不取纸质检验结果。除本项目外，其它检查项目**必须**取纸质检验结果单。

以下为性激素五项检查结果样式示意图

![检查结果样式-激素五项](https://user-images.githubusercontent.com/70079806/214482278-6b5b13a3-cafc-4d2f-b844-2ed85873cf14.jpeg)

</details>

5. 检查费用账单

<details>
<summary>检查费用账单</summary>
以下为检查费用账单图

![检查费用](https://user-images.githubusercontent.com/70079806/214482290-b5463b9f-0e77-4b96-b831-93e4c2c921fc.jpeg)
</details>

病历打印：
出证当天即可在大连七院***7号楼***（医院正门进门后第一个路口左转）打印，***无需等待一周***，需缴纳1元打印费用，需微信扫码现场缴费，***不在小程序中缴费***。

<details>
<summary>证明打印</summary>

出具性别不一致（易性症）证明后，在大连七院***门诊楼一楼4号挂号窗口***交36元打印证明

以下为证明打印账单图

![证明打印费用](https://user-images.githubusercontent.com/70079806/214482306-15ce7dbd-c689-4bf6-a382-f8c75c537809.jpeg)

</details>

<details>
<summary>病历样式</summary>

以下为病历样式示意图

![病历样式-P1](https://user-images.githubusercontent.com/70079806/214482253-60189006-d323-47b5-9762-921bd1d851c6.jpeg)

![病历样式-P2](https://user-images.githubusercontent.com/70079806/214482241-99e97231-e22e-4301-bd4f-359da4409985.jpeg)

</details>

<details>
<summary>证明样式</summary>

以下为性别不一致（易性症）证明样式示意图

![性别不一致证明样式](https://user-images.githubusercontent.com/70079806/214482281-e3ee908d-5bf8-4bd7-ad58-bfda1d2d4b24.jpeg)

</details>

<details>
<summary>详细费用</summary>

所有费用总和为996元，包括：挂号费+首诊费+检查费+证明打印费+病历打印费用。

以下为具体的诊疗账单

![挂号记录](https://user-images.githubusercontent.com/70079806/214482294-74fa2332-4339-440e-ab67-ca0bfc889d42.jpeg)

</details>

<details>
<summary>门诊缴费记录</summary>

![门诊缴费记录](https://user-images.githubusercontent.com/70079806/214482287-9d9ab5ef-ac8d-4801-83fb-71d94bfec2d1.jpeg)

</details>

**Comment by Arlia-Etoile** [comment]
贡献者信息：
- Arlia Étoile<br>Twitter@Arlia_etoile<br>Mastodon@arlia@alive.bar
- 泉戸 こはく<br>Twitter@kohakumito<br>Mastodon@mitokohaku@alive.bar

**Comment by Arlia-Etoile** [comment]
信息获得时间：2023年1月中旬
信息来源：贡献者前往就诊获得

**Comment by Arlia-Etoile** [comment]
#update_require

**Comment by LeeGuanLi** [comment]
> 信息获得时间：2023年1月中旬 信息来源：贡献者前往就诊获得

七院多了激素五项和脑ct欸，以前400内全套到手。。

**Comment by Arlia-Etoile** [comment]
> > 信息获得时间：2023年1月中旬 信息来源：贡献者前往就诊获得
> 
> 七院多了激素五项和脑ct欸，以前400内全套到手。。

是的，4个月就涨价了一倍（之前小雪10月左右发的400元能搞定）

**Comment by LeeGuanLi** [comment]
> > > 信息获得时间：2023年1月中旬 信息来源：贡献者前往就诊获得
> > 
> > 
> > 七院多了激素五项和脑ct欸，以前400内全套到手。。
> 
> 是的，4个月就涨价了一倍（之前小雪10月左右发的400元能搞定）

不过对本地孩子来说问题不大，医保统筹可以报销60%-70%

**Comment by LeeGuanLi** [comment]
> > > > 信息获得时间：2023年1月中旬 信息来源：贡献者前往就诊获得
> > > 
> > > 
> > > 七院多了激素五项和脑ct欸，以前400内全套到手。。
> > 
> > 
> > 是的，4个月就涨价了一倍（之前小雪10月左右发的400元能搞定）
> 
> 不过对本地孩子来说问题不大，医保统筹可以报销60%-70%

（这是今年新政策

**Comment by Arlia-Etoile** [comment]
> > > > 信息获得时间：2023年1月中旬 信息来源：贡献者前往就诊获得
> > > 
> > > 
> > > 七院多了激素五项和脑ct欸，以前400内全套到手。。
> > 
> > 
> > 是的，4个月就涨价了一倍（之前小雪10月左右发的400元能搞定）
> 
> 不过对本地孩子来说问题不大，医保统筹可以报销60%-70%

羡慕有本地医保的，外地的就没办法了。。。

**Comment by LeeGuanLi** [comment]
> > > > > 信息获得时间：2023年1月中旬 信息来源：贡献者前往就诊获得
> > > > 
> > > > 
> > > > 七院多了激素五项和脑ct欸，以前400内全套到手。。
> > > 
> > > 
> > > 是的，4个月就涨价了一倍（之前小雪10月左右发的400元能搞定）
> > 
> > 
> > 不过对本地孩子来说问题不大，医保统筹可以报销60%-70%
> 
> 羡慕有本地医保的，外地的就没办法了。。。

确实。。。。

**Comment by LeeGuanLi** [comment]
话说为什么要加[outdated]（过时）标签，内容时效性不是蛮强的

**Comment by Arlia-Etoile** [comment]
> 话说为什么要加[outdated]（过时）标签，内容时效性不是蛮强的

因为原词条的时效性过期了，而且update_required在issues 反馈通道里没找到，那堆里面只有outdated 最贴近

**Comment by Arlia-Etoile** [comment]
@saeziae @kenchiu233 山前姐、可橙姐更新啊

**Comment by kenchiu233** [comment]
喵～？

**Comment by Arlia-Etoile** [comment]
已经提交有一段时间了，但是wiki里还没有更新

**Comment by septs** [comment]
@Arlia-Etoile 考虑到图片的垂直空间较长，故对 issue 内容做了折叠处理

另外本篇报告更加类似于个人笔记，因此将在条目做出引用但不转载内容

同时这样也便于后续读者使用本 issue 与您建立沟通

**Comment by YurinaKagurasaka** [comment]
我想问一下，我去开了证之后，病历上写着要在某天去复诊。这个复诊是必须要去的吗？如果要去的话，复诊的时候要做些什么？需要重新挂号吗？

**Comment by Arlia-Etoile** [comment]
不必须去复诊，如果想去，挂号系统里面好像是有一个复诊挂号的（时间太长记不清了）

**Comment by XUEWUQIUSHUANG** [comment]
想问一下如果在别的医院做过所有检查还需要在这里做一遍吗

**Comment by Arlia-Etoile** [comment]
不清楚，当时去就是初诊，检查在别的地方都没做过
