### ISSUE TITLE
尝试使用去中心化的托管方式来规避访问问题

### ISSUE THREAD

**Issue by monstertsl** [mtf-wiki/MtF-wiki#726]
可以参考文档[将Hugo托管到4everland](https://www.tanging.tk/%E5%B0%86hugo%E6%89%98%E7%AE%A1%E5%88%B04everland/),将网站托管到去中心化平台

**Comment by septs** [comment]
1. 您与 4EVERLAND 是否构成为**利益相关方**？
2. 请证明 4EVERLAND 网络是否可以**脱离** 4EVERLAND, Inc 运行？
3. 请证明 4EVERLAND 在 GCP (Google Cloud Compute) 之外有**非受控基础设施**？
4. 请证明 4EVERLAND 有**利益无关方**建立的支链且不受 4EVERLAND, Inc 影响？
