### ISSUE TITLE
增添“如何在 MMPI-2 上获得更高的 Mf 分”指南

### ISSUE THREAD

**Issue by wmtdru8xip** [mtf-wiki/MtF-wiki#729]
# 描述
中国的许多精神心理科医生常使用 MMPI-2 的 Mf 分来鉴跨，因此个人认为有必要增添一个“如何在 MMPI-2 上获得更高的 Mf 分”的指南。

# 相关内容

## 什么是 MMPI-2
MMPI-2 是明尼苏达多相人格量表第二版（Minnesota Multiphasic Personality Inventory rev. 2）的缩写。

## 什么是 Mf 分
Mf (Masculinity - feminity, 男子气-女子气) 是 MMPI-2 的一个项目，反应被测试者的行为、喜好、情感、性别角色等人格方面的性别表达与社会对其指派性别的期望与刻板印象的不符程度。
其分为 Mf-m（男性女性化，用于指派男性）与 Mf-f（女性男性化，用于指派女性）两种。

## 为什么要在 MMPI 上作假
如果遵循 gender self-identification 原则，跨性别不需任何测试，用某一类量表鉴跨来阻碍跨性别者获得医学治疗显然是不正确的。
即使不遵循 self-id，性别认同仍是一件个人的事情，与是否符合社会的期望无关。社会没有权利将女性“变成”男性或将男性“变成”女性，仅因为某个人不符合其期望。因此，量表测试仍应以个人认同与感受为准（如 UGDS、GIDYQ 等），而非对社会期望的满足程度（如 MMPI）。
综上，使用 MMPI 来鉴跨是无意义的，且是对跨性别权利的侵犯。这不是说 MMPI 本身有问题，而是说，国内医院的使用方式有误。用 MMPI 来鉴跨，正如使用焦虑量表来评抑郁，或用抑郁量表来评焦虑一样。
因此，如果医生使用 MMPI 来鉴跨，我们完全有正当的理由来反对它。

## 注意事项
MMPI 有数个效度分，可有效地检测出大部分欺骗的尝试。因此，除非详细研究过此量表，不要尝试在其他方面作假。
除以下涉及到的题目外的一切题目，请按真实情况回答。
通常，国内开病历或证明需要 Mf 的T分达 65 分或更高。但是，注意不要高于85，以免显得过分夸张（除非你的实际情况如此）。

#### 回答“是”时记一分，反之记零分：
我想我会喜欢图书馆员的工作。
我想成为一名歌手。
（如果你不是女孩）我经常希望我是一个女孩。（或者，如果你是女孩）我从来没有为自己是女孩而感到过遗憾。
我喜欢读爱情故事。
我喜欢诗歌。
我想成为一名花匠。
我想当护士。
我喜欢戏剧。
我喜欢收集鲜花或种植室内植物。
有时，我的思维比我的语言要快。
我喜欢做饭。
我曾经写日记。
我担心性的问题。
我的手没有变得笨拙或不灵活。
如果我是记者，我非常想报告剧院的新闻。
我想成为一名记者。
我经常发现自己担心某事。
我的一些家庭成员有十分影响我和使我烦恼的习惯。
我喜欢谈论性。
我对爱情感到失望。
如果我是一名艺术家，我会喜欢画花。
我经常觉得陌生人在批判性地看着我。
偶尔，我恨我通常喜欢的家庭成员。
我希望我不会被有关性的想法所困扰。
我认为我的感受比大多数人的更强烈。

#### 回答“是”时记零分，反之记一分：
我喜欢有关机械的杂志。
当我从事新工作时，我想弄清应亲近谁。
我觉得当我遇到麻烦时，最好的办法显然是闭嘴。
当人们伤害我时，我觉得我应该报复它们，只是为了原则。
我的感受不易受到伤害。
我有时会捉弄动物。
我想我会喜欢护林员所做的那种工作。
说服大多数人真相需要很多争论。
我喜欢参加聚会和其他大量乐趣的事。
我会更喜欢我下了赌注的比赛或游戏。
大多数人之所以诚实，主要是因为他们害怕被发现。
我的餐桌礼仪在家中不如我在外时那样好。
我经常发现有我必要为我认为正确的事情而坚持己见。
我从来没有沉迷于不寻常的性行为。
我相信有来世。
我想成为一名士兵。
我对蛇没有太大的恐惧。
我很少做白日梦。
在走路时，我非常小心地跨过人行道的裂缝。
我从来没有为任何皮肤上长的东西而担心过。
我想我会喜欢建筑承包商的工作。
我喜欢科学。
我非常喜欢狩猎。
我会喜欢归属于好几个俱乐部。
我喜欢和一群互开玩笑的人在一起。
我在学校学习得很慢。
我不为我的长相不好而担忧。
我完全自信。
大多数人结交朋友是因为朋友可能对他们有用。
如果我是记者，我会非常喜欢报告体育新闻。
我一生中从来没有一段时间喜欢过玩洋娃娃。

#### 原始分至T分转换数据：
``` text
17 30
18 32
19 34
20 36
21 38
22 40
23 42
24 44
25 46
26 48
27 50
28 52
29 54
30 56
31 58
32 60
33 62
34 64
35 66
36 68
37 70
38 72
39 72
40 76
41 78
42 79
43 81
44 83
45 85
46 87
47 89
48 91
49 93
50 95
51 97
52 99
53 101
54 103
55 105
56 107
57 109
```

#### 回答“是”时记一分，反之记零分：
我想我会喜欢图书馆员的工作。
我想成为一名歌手。
（如果你不是女孩）我经常希望我是一个女孩。（或者，如果你是女孩）我从来没有为自己是女孩而感到过遗憾。
我喜欢读爱情故事。
我喜欢诗歌。
我想成为一名花匠。
我想当护士。
我喜欢戏剧。
我喜欢收集鲜花或种植室内植物。
我从来没有沉迷于不寻常的性行为。
有时，我的思维比我的语言要快。
我喜欢做饭。
我曾经写日记。
我的手没有变得笨拙或不灵活。
如果我是记者，我非常想报告剧院的新闻。
我想成为一名记者。
我经常发现自己担心某事。
我的一些家庭成员有十分影响我和使我烦恼的习惯。
我对爱情感到失望。
如果我是一名艺术家，我会喜欢画花。
我经常觉得陌生人在批判性地看着我。
偶尔，我恨我通常喜欢的家庭成员。
我认为我的感受比大多数人的更强烈。

#### 回答“是”时记零分，反之记一分：
我喜欢有关机械的杂志。
当我从事新工作时，我想弄清应亲近谁。
我觉得当我遇到麻烦时，最好的办法显然是闭嘴。
当人们伤害我时，我觉得我应该报复它们，只是为了原则。
我的感受不易受到伤害。
我有时会捉弄动物。
我想我会喜欢护林员所做的那种工作。
说服大多数人真相需要很多争论。
我喜欢参加聚会和其他大量乐趣的事。
我会更喜欢我下了赌注的比赛或游戏。
大多数人之所以诚实，主要是因为他们害怕被发现。
我的餐桌礼仪在家中不如我在外时那样好。
我经常发现有我必要为我认为正确的事情而坚持己见。
我从来没有沉迷于不寻常的性行为。
我相信有来世。
我想成为一名士兵。
我对蛇没有太大的恐惧。
我担心性的问题。
我很少做白日梦。
在走路时，我非常小心地跨过人行道的裂缝。
我从来没有为任何皮肤上长的东西而担心过。
我想我会喜欢建筑承包商的工作。
我喜欢科学。
我非常喜欢狩猎。
我会喜欢归属于好几个俱乐部。
我喜欢谈论性。
我喜欢和一群互开玩笑的人在一起。
我在学校学习得很慢。
我不为我的长相不好而担忧。
我完全自信。
大多数人结交朋友是因为朋友可能对他们有用。
如果我是记者，我会非常喜欢报告体育新闻。
我希望我不会被有关性的想法所困扰。
我一生中从来没有一段时间喜欢过玩洋娃娃。

#### 原始分至T分转换数据：
``` text
8 120
9 118
10 116
11 114
12 111
13 109
14 106
15 104
16 101
17 99
18 96
19 94
20 92
21 89
22 87
23 84
24 82
25 79
26 77
27 74
28 72
29 69
30 67
31 65
32 62
33 60
34 57
35 55
36 52
37 50
38 47
39 45
40 43
41 40
42 38
43 35
44 33
45 30
```

#### 计算你的原始分，然后查转换数据得出T分。
如果得分过低，请修改自己的部分回答，然后再次计算，直到分数足够为止。

多次阅读并熟记问题及你的回答，直到你看到问题时可以立刻反应出来。
找一个测试网站，进行 MMPI-2 测试，有可能要付钱。英文好的人可以到 GitHub 上找开源的项目来测试（都是英文）。
最后，检查 Mf 分是否符合要求。

### 以 CC-BY-SA 4.0 协议分发
MMPI-2 内容版权由明尼苏达州大学持有，此处引用应属于 fair use。
其他内容以 CC-BY-SA 4.0 or CC0 1.0 许可协议分发。

**Comment by wmtdru8xip** [comment]
不知道是否有医生会看 GF 和 GM。如果需要的话，我会在有时间时添加 GF / GM 指导。

**Comment by septs** [comment]
@MlgmXyysd

**Comment by wmtdru8xip** [comment]
（我自己就是被 MMPI 卡住的）

**Comment by tuboshufps** [comment]
https://github.com/SHENGYUKing/MMPI_Test
mmpi的程序与答案（也许需要一丁点py代码阅读能力）
但个人认为操控量表是不尊重医学，不尊重医师的方式，滥用此方法也许会导致开证门槛进一步提高，尽管这确实会让你更容易拿到证明/处方。

**Comment by saeziae** [comment]
我認爲操控mmpi量表結果無傷大雅。既然是不合理的鑑跨行爲，無妨去破壞它。

**Comment by MlgmXyysd** [comment]
- 该内容会间接导致 MMPI 及 MMPI-2 无法采信，并可能会导致开证门槛提高。
- MtF.Wiki 具有指导性，该内容不宜使用 MtF.Wiki 作为载体进行广泛传播。
- 据反馈及资料显示，国内大部分医院目前仍使用 MMPI，MMPI-2 并未被广泛应用。且多数医院仅将量表内容作为参考，并不作为唯一开证依据。
- MMPI 及 MMPI-2 相关量表中题目描述内容符合社会公认的性别相关兴趣特色及行为方式，鉴跨是为了更好的被社会接纳，对于 RLE 具有一定的积极意义，应当辩证看待。
- 根据手边资料整理，第二版与原始版整体改动较大，其中 Mf 量表改动了 6 道题目，删除了 4 道题目。VRIN 与 TRIN 为 MMPI-2 新增量表。
- 对于 MMPI 及 MMPI-2 的研究应专注于修正翻译误差，而非操纵量表分数：如 MMPI 295 题（在 MMPI-2 中被删除），及 MMPI 81 题（在 MMPI-2 中为 69 题）。
- 目前正在参与相关资料及中外文献的整理研究，将在完成后以在线测试分析和资料参考的形式独立发布于 ReadMe Over a Coffee。

**Comment by LeeGuanLi** [comment]
此方式可能会增加开征门槛，不建议在Wiki传播，有相关需要自行在知乎查找即可。
且本人亲测mf分只需多做几遍就可大概掌控，本友跨顺男标准分80+，分数不高自行注意一下刻板印象题即可，没必要刻意背题。

**Comment by Hanaajanen** [comment]
我在刷mmpi的前夜做了一次95分，结果现场去做的时候做出了108分
有些刻板印象的题目都是一眼丁真的

**Comment by septs** [comment]
考虑到目前中国大陆境内多数“精神科”使用 MMPI 量表作为评价依据之一

不仅适用于跨性别，在量表结果上进行作假可能使得量表实践退化成 1 对 1 的方式进行而非自主进行

**Comment by Cryolitia** [comment]
> MMPI 及 MMPI-2 相关量表中题目描述内容符合社会公认的性别相关兴趣特色及行为方式，鉴跨是为了更好的被社会接纳，对于 RLE 具有一定的积极意义，应当辩证看待。

MMPI基于上世纪40年代的北美白人的统计结果，在跨时间跨地域跨文化的环境下指导跨性别的RLE过于搞笑，更不用说其中包含了大量的关于个人职业选择的评判，这也不利于进一步鼓励学科间的性别平等。作为给后来这个讨论的人参考我更推荐 RLE.wiki，甚至《药娘的天空》都比MMPI更为靠谱。

> 我認爲操控mmpi量表結果無傷大雅。既然是不合理的鑑跨行爲，無妨去破壞它。

我支持 saeziae 阁下的观点，但因此帖争议过大，且容许我进一步搁置讨论，暂时不作出相应改变。

个人建议是可以不明确涉及性别相关议题的情况下另开repo或网站详细介绍MMPI的题目与赋分标准。

**Comment by BeiyanYunyi** [comment]
> 该内容会间接导致 MMPI 及 MMPI-2 无法采信，并可能会导致开证门槛提高。

作为退子不挺希望 gate keeping 把“虚假的”跨子拒之门外吗？感觉不如支持 MMPI 模拟来一把加速。

**Comment by yingxue03** [comment]
> * 该内容会间接导致 MMPI 及 MMPI-2 无法采信，并可能会导致开证门槛提高。

> * MMPI 及 MMPI-2 相关量表中题目描述内容符合社会公认的性别相关兴趣特色及行为方式，鉴跨是为了更好的被社会接纳，对于 RLE 具有一定的积极意义，应当辩证看待。

https://web.archive.org/web/20210509021732/limelight.moe/t/topic/3015 :

> 嗯，Mf 是 MMPI 里面少有的分男女的项目。看到两个原始分分布反转就该知道 T 分高低测量的是“不符合刻板印象的程度”，倒也是挺符合这东西拿来抓同性恋的历史意义的。
> 
> 两边的差距也是很有趣：
> posM → posF: +121, -166, -209, -268
> negM → negF: -121, +166, +209, +268
> 
> 为什么这四道题目会反转男女特性呢？我们来看看对应的问题：
> 
> 121. I have never indulged in unusual sex practices.
>      我从来没做过很奇怪的爱。[F+]
> 166. I am worried about sex.
>      我对羞羞的事情很担心。[T+]
> 209. I like to talk about sex.
>      我喜欢谈论做爱做的事！[T+]
> 268. I wish I were not bothered by thoughts about sex.
>      我希望我可以不受有关 H 的想法困扰。[T+]
> 
> 啧，都是找……「性变态」……的题目啊。怪不得要两边都改成对 Mf 效果相同的方向呢。正好，大家都是变态，白拿 4 个原始分。
> 
> 剩下的题目就是一些比较经典的刻板印象题，例如工程制图（M）、图书馆员（F）、精准拍马（M）、当众唱歌（F）、闷声发财（M）、以牙还牙（M）、想当女生（F）这种。这种东西拿来预测性别认同有多旧社会我们都知道，但至少是没有挂羊头卖狗肉……吧？

这种东西有什么可采信的。那四道「性变态」题也加 Mf 分，用这个来指导如何「更好的被社会接纳」是吗？

**Comment by yingxue03** [comment]
https://zqb.cyol.com/content/2002-07/24/content_497432.htm （2002年7月24日）

> 　 一位已过而立之年的女青年冷静地说：“不能否认，有些病人为达到做手术的目的，确实对医生说了谎话，比如问是不是厌恶自己的性器官？就说是。是不是厌恶同性恋行为？也说是。反正目的是做手术。有的女孩子在做手术前还和男人有性关系，但医生很难了解，其实如果让我们自己来确认倒可能更准一些，因为病人只在和自己有相同身份的人面前才讲真话。中国长期存在重男轻女的传统观念，还有一些人作为女人本身条件不大好，或者有同性恋倾向，也是她们做变性手术的原因，但这当中确实有像我一样真正的易性癖。”
> 
> 　 另一位做相反方向变性手术的男青年告诉我：“什么心理和精神治疗，让我们做的那个心理测试就算是了，对我来说很容易，我太明白为什么提那种问题了，我轻而易举就得了高分。如果过不去，说明智商太低，再说只要想做手术，花点钱开个证明有什么难？” 

你圈没有新鲜事.jpg

**Comment by yingxue03** [comment]
Appleby, Thomas Loring and Haner, Charles F. (1956) "MMPI Profiles of a College Faculty Group," Proceedings of the Iowa Academy of Science, 63(1), 605-609.
Available at: https://scholarworks.uni.edu/pias/vol63/iss1/66 

> The very high Mf score of the men is perhaps the outstanding feature of the profile. The mean falls almost two SDs above the normative mean for the male faculty group. Examination of the feminine-keyed items of the MMPI suggests why. It is scarcely surprising that faculty men should respond "yes" to such questions as "I like poetry," or "I liked Alice in Wonderland' by Lewis Carroll," or to reply "no" to the question "I believe there is a devil and hell in afterlife." Nor is it surprising that faculty men in music and language and literature should be more feminine in their replies than scientists, and that the physical education group should be the most masculine of all the groups. Even this small group, however, is decidely feminine, falling one standard deviation above the normative mean.

> 男性的Mf得分极高，这或许是该人群特征中最显著的体现。其平均值比男性教职工群体的常模平均值高出近两个标准差。对MMPI中女性化倾向题目的分析或许能解释这一现象。男性教职工对“我喜欢诗歌”或“我喜欢刘易斯·卡罗尔的《爱丽丝梦游仙境》”这类问题回答“是”，或者对“我相信来世有魔鬼和地狱”这类问题回答“否”，这并不令人惊讶。同样，音乐、语言和文学专业的男性教职工比理科专业的男性教职工在回答中更偏向女性化，而体育教育专业的男性教职工群体在所有群体中最具男性化倾向，这也不足为奇。然而，即使是这个小群体，其女性化倾向也十分明显，比常模平均值高出一个标准差。

话说中国民间信仰该怎么回答"I believe there is a devil and hell in afterlife."来着……

> MMPI基于上世纪40年代的北美白人的统计结果，在跨时间跨地域跨文化的环境下指导跨性别的RLE过于搞笑，更不用说其中包含了大量的关于个人职业选择的评判，这也不利于进一步鼓励学科间的性别平等与多元发展。作为给后来这个讨论的人参考我更推荐 [RLE.wiki](https://rle.wiki/) ，甚至《药娘的天空》都比MMPI更为靠谱。

感觉可能不如random网友瞎jb做的“[男娘测试](https://femboy.test.nagisa.icu/)”靠谱……
