### ISSUE TITLE
“办公地点”门牌格式问题

### ISSUE THREAD

**Issue by Aleksanaa** [mtf-wiki/MtF-wiki#734]
### MtF.wiki URL

https://mtf.wiki/zh-cn/about/

### 内容

根据实拍，格式是这样的
![IMG20230204213220](https://user-images.githubusercontent.com/42209822/216771450-258606fb-c1b8-4c22-9521-daec01236768.jpg)

**Comment by saeziae** [comment]
门牌系虚构，勿与现实对号入座，如有雷同纯属巧合

**Comment by Aleksanaa** [comment]
> 门牌系虚构，勿与现实对号入座，如有雷同纯属巧合

可是，您的门牌样式大概是上海，并缝合了一个二维码。
