### ISSUE TITLE
刘烨医生恢复出诊

### ISSUE THREAD

**Issue by daanqwq** [mtf-wiki/MtF-wiki#739]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/hrt/puth/liu-ye/

## 挂号

刘烨医生的出诊时间为

```csv
周次,时间,科室,价格
周三,下午,内科-内分泌门诊-易性症激素治疗门诊 ,60 元
```
**出诊时间不固定，建议自行从相关平台获取近期出诊情况。**

如何挂号详见 [北医三院：预约挂号]({{< ref "puth#register" >}})。

## 青春期阻断剂相关事宜

要求符合易性症诊断，年龄 16 岁以下。需要父母之一签字，花费约每月 2000￥~3000￥．初次 HRT 会要求住院4-5天，住院+前三针花费约10000￥，并在住院时检查骨龄等有关项目。

**Comment by septs** [comment]
Duplicate of #735

CC @MlgmXyysd

**Comment by daanqwq** [comment]
更新青春期阻断剂相关事宜

要求符合易性症诊断，年龄 16 岁以下。需要父母之一签字，花费约每月 2000￥~3000￥．初次 HRT 会要求住院4-5天，住院+前三针花费约10000￥，并在住院时检查骨龄等有关项目。
