### ISSUE TITLE
陕西省精神卫生中心 雷莹

### ISSUE THREAD

**Issue by NaiveTomcat** [mtf-wiki/MtF-wiki#751]
### 医院名称

陕西省精神卫生中心

### 医生姓名

雷莹

### 注意事项

疑似已重新出诊，微信小程序可预约专家号
![IMG_20230223_194253](https://user-images.githubusercontent.com/50436951/220896999-aabfc8e8-25f4-4bb6-99dd-eb571f926925.jpg)

目前未就诊

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by septs** [comment]
至少需要一例独立获得诊断证明的报告再予以处理
