### ISSUE TITLE
关闭

### ISSUE THREAD

**Issue by XyliaUp** [mtf-wiki/MtF-wiki#765]

**Comment by septs** [comment]
希望提供病历照片[^1]等材料，作为辅证

[^1]: 建议使用 Microsoft Lens 进行拍摄

**Comment by XyliaUp** [comment]
![Uploading FA825972-3395-4759-92A1-EEBCEA5C3E33.jpeg…]()

**Comment by XyliaUp** [comment]
> 希望提供病历照片[1](#user-content-fn-1-0fbeef35594fa503cc3754cc62aef68c)等材料，作为辅证，提高报告的可信度
> 
> ## Footnotes
> 1. 建议使用 Microsoft Lens 进行拍摄 [↩](#user-content-fnref-1-0fbeef35594fa503cc3754cc62aef68c)

![1B4CAFD6-5410-4A72-A8AC-279DA67AE502](https://user-images.githubusercontent.com/43511972/224550821-0f1e3184-28c1-43cb-9df4-6fd8b494bb4f.jpeg)
![514BCE75-D9DA-4CDC-831C-BA27AD1380BD](https://user-images.githubusercontent.com/43511972/224550824-d05cb2cb-03fb-47d3-b1c5-e66158234b0e.jpeg)
