### ISSUE TITLE
建议增加 "未来科技展望" 栏目

### ISSUE THREAD

**Issue by sceext2** [mtf-wiki/MtF-Wiki#86]
如题, 建议增加 "未来科技展望" 栏目, 具体栏目名称可以再讨论.

主要内容包括对本群体意义 (特别) 重大的 (生物医学) 研究领域.

目的是给许多人希望, 表明前途是光明的 (道路是曲折的), 并且在有生之年就有许多值得期待的事情发生, 鼓励大家努力生活下去.

## 具体形式

栏目包括一篇目录 (导读), 以及若干篇文章.

每篇文章包括一篇相关论文, 内容包括论文链接 (引用), 论文部分内容的翻译 (因为论文一般是英文的), 比如论文摘要, overview (第一章), 结论 (最后一章), 以及中间的精彩片段.
由于原论文一般很长, 并且内容较专业, 因此没必要全部翻译, 只需翻译一小部分即可.  感兴趣的读者可以自行查阅原文.

## 注意事项

1. 必须基于正式公开发表的论文, 且避免具有很大争议的论文 (比如学术造假).
2. 文章内容不得超出原论文所表达的含义范围, 也就是避免自行添油加醋.
3. 必须包含原论文的链接或引用, 链接或引用必须正确, 确保读者能查到原论文.

## 话题举例

举个栗子, 可以考虑这些话题:  

+ 人造子宫相关 (体外胚胎培养, 别的哺乳动物比如小鼠, 牛羊都可以)  

+ 雄性小鼠移植子宫并成功生下健康小鼠  

+ 小鼠多能干细胞诱导培养出卵细胞 (以及卵巢基质细胞)  

以上.

**Comment by septs** [comment]
本编辑观点：我认为只应当记录既定事实

对于正在探索的技术路线不应当广泛宣传以免造成因阅读理解导致的理解偏差
